digitallyinduced/ihp

IHP/ValidationSupport/ValidateField.hs
NixSupport/shell.nix
Test/ValidationSupport/ValidateFieldSpec.hs
ihp.cabal
ihp.nix

This adds more validators, including tests.

More validators

---

lib/IHP/static/ihp-codegen.css

Fix rounded borders on Codegen

---

Guide/hsx.markdown
IHP/HtmlSupport/Parser.hs
IHP/HtmlSupport/QQ.hs

Fixes #83.
`{...attributes}` syntax also going to be added to this branch before merging.

HSX now has improved support for html boolean attributes

---

IHP/ErrorController.hs
IHP/IDE/SchemaDesigner/Compiler.hs
IHP/IDE/SchemaDesigner/Controller/EnumValues.hs
IHP/IDE/SchemaDesigner/Controller/Tables.hs
IHP/IDE/SchemaDesigner/Parser.hs
IHP/IDE/SchemaDesigner/Types.hs
IHP/IDE/SchemaDesigner/View/Columns/Edit.hs
IHP/IDE/SchemaDesigner/View/Layout.hs
IHP/SchemaCompiler.hs
Test/IDE/SchemaDesigner/CompilerSpec.hs
Test/IDE/SchemaDesigner/ParserSpec.hs
Test/Main.hs
Test/ValidationSupport/ValidateFieldSpec.hs

Fixed enums

---

Guide/installation.markdown

@jeyj0 can you quickly take a look over this?

Improved installation steps for nixos

---

ProjectGenerator/bin/ihp-new

Added option to install git and make automatically if not installed beforehand

---

Guide/database.markdown

fixed type

---

Guide/authentication.markdown

This adds information about adding `currentUser` to the view context, and removes the use of `User.name` since the provided example SQL doesn't have a `name` field.

update authentication documentation

---

IHP/IDE/Postgres.hs

Fixed postgres not always initalized

---

IHP/IDE/SchemaDesigner/Controller/Schema.hs
IHP/IDE/SchemaDesigner/View/Tables/Index.hs

Show an error message when db update fails

---

IHP/QueryBuilder.hs

Idea taken from https://www.youtube.com/watch?v=j0BYHDlLJtY

Added orderByAsc as an alias for orderBy

---

IHP/IDE/ToolServer.hs
IHP/Server.hs

This reverts commit 9240edda89a3c256cd2c0830de415a90601edba7 :cry:

Revert "use session store, even on Linux"

---

Guide/routing.markdown

The custom routing example appears to parse routes incorrectly.

Fix Real-World custom routing example

---

IHP/SchemaCompiler.hs

Variations in naming of field names and type arguments were breaking the logic
for generating instances in the SchemaCompiler. This led to broken fetchRelated
functionality when referencing tables had multiple words in their names. This is
a relatively simple and neat way to clean up those issues.
Fixes #211

[#211] Normalise field names and type arguments in SchemaCompiler

---

IHP/IDE/CodeGen/Controller.hs
IHP/IDE/SchemaDesigner/View/Layout.hs
IHP/IDE/ToolServer/Types.hs
IHP/IDE/ToolServer/ViewContext.hs

[SchemaDesigner] Don't Show Generate or Show Controller when it does or doesn't exist

---

Guide/recipes.markdown
IHP/IDE/ToolServer.hs

Open the local dev url in an async way

---

IHP/CLI/NewApplication.hs
IHP/IDE/CodeGen/ApplicationGenerator.hs
IHP/IDE/CodeGen/Controller.hs
IHP/IDE/CodeGen/Types.hs
IHP/IDE/CodeGen/View/Generators.hs
IHP/IDE/CodeGen/View/NewApplication.hs
IHP/IDE/ToolServer/Types.hs

Added Application Generator to CodeGen

---

IHP/IDE/CodeGen/ActionGenerator.hs
IHP/IDE/CodeGen/Controller.hs
IHP/IDE/CodeGen/View/Generators.hs
IHP/IDE/CodeGen/View/NewAction.hs
lib/IHP/static/ihp-codegen.css

Action Generator option for corresponding view

---

Guide/Makefile
Guide/layout.html
Guide/updating.markdown

Fixes https://github.com/digitallyinduced/ihp/issues/78

Added section "How to update IHP?"

---

IHP/IDE/CodeGen/Controller.hs
IHP/IDE/CodeGen/ControllerGenerator.hs
IHP/IDE/CodeGen/View/NewAction.hs
IHP/IDE/CodeGen/View/NewController.hs
IHP/IDE/CodeGen/View/NewView.hs
IHP/IDE/ToolServer/ViewContext.hs

Issue 199/generators application aware

---

IHP/ModelSupport.hs
IHP/SchemaCompiler.hs

We now:
- Keep track of fields that are set in the `touchedFields` attribute of the `meta` field
- Use the `touchedFields` to correctly use the `DEFAULT` SQL value
- Use the `touchedFields` to only update new values in `updateRecord`

Improve Create and UpdateRecord

---

Guide/hsx.markdown
IHP/ErrorController.hs
IHP/HtmlSupport/Parser.hs
IHP/HtmlSupport/QQ.hs

Fixes https://github.com/digitallyinduced/ihp/issues/249

Hsx script and style

---

IHP/HtmlSupport/Parser.hs

[#223] Add support for void tags without trailing slash

---

IHP/Controller/Param.hs
IHP/ModelSupport.hs

Fixes https://github.com/digitallyinduced/ihp/issues/255

Added missing InputValue and ParamReader instances for Day type

---

IHP/HaskellSupport.hs
IHP/ModelSupport.hs
IHP/RouterSupport.hs
IHP/ValidationSupport/ValidateField.hs

This fixes the very old https://app.clubhouse.io/digitallyinduced/story/300/didchange-helper :-) Made possible by recently adding the `touchedFields` to `MetaBag` 🎉

Added includes, didChange, didChangeRecord

---

IHP/IDE/CodeGen/ControllerGenerator.hs
IHP/IDE/CodeGen/ViewGenerator.hs
IHP/NameSupport.hs

Fixes https://github.com/digitallyinduced/ihp/issues/262

Fixed code generators not dealing well with underscores

---

ProjectGenerator/bin/ihp-new

Fixes https://github.com/digitallyinduced/ihp/issues/247

Added "--help" option to ihp-new command

---

IHP/View/Form.hs

renderBootstrapFormField updated to use the new datetime-local field type.

datetime-local field change missing on renderBootstrapFormField

---

Guide/relationships.markdown

On gitter it was pointed out that this section was not up to date with the real implementation 👍

Updated relationships doc to include belongs to relationships

---

IHP/Controller/Render.hs

Adds Content-Type Headerfield to the responses send with renderPlain

Add Content-Type Header to renderPlain

---

Guide/Makefile
Guide/editors.markdown
Guide/layout.html
Guide/recipes.markdown

Fixes https://github.com/digitallyinduced/ihp/issues/276

Added new docu section "Editors & Tooling"

---

.github/workflows/build.yml
.github/workflows/build_mac.yml
.github/workflows/build_test.yml
ProjectGenerator/bin/ihp-new

This is to address https://github.com/digitallyinduced/ihp/issues/265

use qualified nixpkgs attribute paths to avoid large evaluations

---

Guide/database.markdown
IHP/ModelSupport.hs

Fixes https://github.com/digitallyinduced/ihp/issues/283

Added deleteAll and truncate the output of deleteRecords with many records

---

IHP/ErrorController.hs

Fixes https://github.com/digitallyinduced/ihp/issues/285

Print exception to stdout additionally to rendering it into the browser

---

IHP/IDE/Data/View/Layout.hs
IHP/IDE/SchemaDesigner/Compiler.hs
IHP/IDE/SchemaDesigner/Controller/Tables.hs
IHP/IDE/SchemaDesigner/Parser.hs
IHP/IDE/SchemaDesigner/Types.hs
Test/IDE/CodeGeneration/ControllerGenerator.hs
Test/IDE/CodeGeneration/ViewGenerator.hs
Test/IDE/SchemaDesigner/CompilerSpec.hs
Test/IDE/SchemaDesigner/ParserSpec.hs

Fixes https://github.com/digitallyinduced/ihp/issues/232

Unique constraints

---

IHP/IDE/CodeGen/ControllerGenerator.hs
IHP/IDE/CodeGen/Types.hs
IHP/IDE/CodeGen/ViewGenerator.hs

Fixes https://github.com/digitallyinduced/ihp/issues/308

Fixed generated controller and forms not containing fields that have a default value (#308)

---

Guide/routing.markdown
IHP/RouterSupport.hs

https://github.com/digitallyinduced/ihp/issues/332

Improved error message `AutoRoute: Failed parsing UUID`

---

IHP/IDE/CodeGen/Controller.hs

Fix Double Imports from Controller Generator

---

Guide/your-first-project.markdown

Whilst reading the excellent `Creating Your First Project`, I noticed a few small grammatical errors / potential changes which I noted and used to make this PR.

Grammer suggestions/corrections

---

IHP/SchemaCompiler.hs

Fixed encoding issue caused by misuse of ByteString causing troubles for enums with special chars

---

Guide/hsx.markdown
IHP/HtmlSupport/Parser.hs

Fixes https://github.com/digitallyinduced/ihp/issues/342

Added support for empty attributes to hsx

---

IHP/IDE/CodeGen/ControllerGenerator.hs
IHP/IDE/CodeGen/Types.hs
IHP/IDE/CodeGen/ViewGenerator.hs
IHP/IDE/Data/Controller.hs
IHP/IDE/Data/View/EditRow.hs
IHP/IDE/Data/View/EditValue.hs
IHP/IDE/Data/View/NewRow.hs
IHP/IDE/Data/View/ShowTableRows.hs
IHP/IDE/SchemaDesigner/Compiler.hs
IHP/IDE/SchemaDesigner/Controller/Columns.hs
IHP/IDE/SchemaDesigner/Controller/Tables.hs
IHP/IDE/SchemaDesigner/Parser.hs
IHP/IDE/SchemaDesigner/Types.hs
IHP/IDE/SchemaDesigner/View/Columns/Edit.hs
IHP/IDE/SchemaDesigner/View/Columns/EditForeignKey.hs
IHP/IDE/SchemaDesigner/View/Columns/New.hs
IHP/IDE/SchemaDesigner/View/Columns/NewForeignKey.hs
IHP/IDE/SchemaDesigner/View/Layout.hs
IHP/IDE/SchemaDesigner/View/Tables/Show.hs
IHP/IDE/ToolServer/Types.hs
IHP/LoginSupport/Middleware.hs
IHP/QueryBuilder.hs
IHP/SchemaCompiler.hs
Test/IDE/CodeGeneration/ControllerGenerator.hs
Test/IDE/CodeGeneration/ViewGenerator.hs
Test/IDE/SchemaDesigner/CompilerSpec.hs
Test/IDE/SchemaDesigner/ParserSpec.hs

[#291] Allow composite primary keys

---

ProjectGenerator/bin/ihp-new

This is a very interesting framework!
I'm just getting started with it this afternoon, but figured I could still make this minor fix.

Fix Grammar

---

Guide/controller.markdown
IHP/AuthSupport/Controller/Sessions.hs
IHP/Controller/Session.hs
IHP/ControllerSupport.hs
IHP/LoginSupport/Helper/Controller.hs

Fixes https://github.com/digitallyinduced/ihp-forum/issues/6 and improves a few other things (see commits :) )

Auth fixes

---

IHP/QueryBuilder.hs

Currently this code:
|> orderBy #lastname
|> orderBy #firstname
has a bug: it will order by the last clause (#firstname) only.
This commit adds support for such nested order bys.

Support for nested ORDER BYs

---

IHP/AuthSupport/Controller/Sessions.hs

Auth: normalize login error message

---

Guide/controller.markdown
IHP/Controller/Param.hs

Fixes https://github.com/digitallyinduced/ihp/issues/389

Added paramList function to deal with multiple params with the same name

---

IHP/IDE/CodeGen/ApplicationGenerator.hs

codgen: remove duplicate FrontController generation statement

---

Guide/recipes.markdown
IHP/ModelSupport.hs

Added textToId function

---

Guide/authentication.markdown
exe/IHP/CLI/HashPassword.hs
ihp.cabal

Added new hash-password command to allow pw hash generation from the terminal

---

IHP/FrameworkConfig.hs
IHP/IDE/ToolServer.hs
IHP/Server.hs

Fixes https://github.com/digitallyinduced/ihp/issues/401
@HugoPeters1024 could you take a look? :)

Session Cookie: HttpOnly + secure

---

IHP/View/Form.hs

Add number input fields.

---

Troubleshoot/README.md
Troubleshoot/ihp-troubleshoot

Fixes https://github.com/digitallyinduced/ihp/issues/413

Added first version of ihp-troubleshoot command

---

Guide/editors.markdown

Doc what Emacs packages work w/IHP, how to get ghci path of direnv

---

IHP/IDE/Data/Controller.hs
IHP/IDE/Data/View/EditRow.hs
IHP/IDE/Data/View/EditValue.hs
IHP/IDE/Data/View/Layout.hs
IHP/IDE/Data/View/NewRow.hs
IHP/IDE/ToolServer/Types.hs
lib/IHP/static/ihp-schemadesigner.js

Data editor refactor

---

IHP/ModelSupport.hs
IHP/PGNotify.hs
IHP/SchemaCompiler.hs
IHP/ScriptSupport.hs
IHP/Server.hs
NixSupport/pkgs.nix
NixSupport/shell.nix
ihp.cabal
ihp.nix

Db connection pool

---

Guide/authentication.markdown
Guide/authorization.markdown

----
This worked for me, would love to find out if it's wrong :-)

Document differences between user vs admin auth

---

IHP/IDE/Logs/Controller.hs
IHP/IDE/StatusServer.hs
IHP/IDE/Types.hs
exe/IHP/IDE/DevServer.hs

Fixes https://github.com/digitallyinduced/ihp/issues/488

Devserver improvements

---

ProjectGenerator/bin/ihp-new

`BIN_DIR/LIB_DIR` were not exported nor used, so deleted.
----
Nothing serious, but it's always a good idea to avoid warning-blindness :)

Fix shellcheck warnings

---

ProjectGenerator/bin/ihp-new

(But keep going if chmod fails for whatever reason)

Set right .ghci permissions for user in ihp-new

---

Guide/Makefile
Guide/design-goals.markdown
Guide/layout.html
Guide/troubleshooting.markdown

This moves the two wiki pages into the guide, allowing external
contributions to these by PRs.
This fixes #513
First PR

Move wiki pages to guide

---

IHP/View/CSSFramework.hs

(Or, if this shouldn't be possible, perhaps the doc's should mention that where checkboxField is mentioned.)

Actually use user-specified labelClass on checkboxField

---

IHP/IDE/CodeGen/MailGenerator.hs
Test/IDE/CodeGeneration/MailGenerator.hs

Fixes #530. Also updated tests to use a different wording, just to be sure :)

Fixed mail generator using hard coded ConfirmationMail name

---

IHP/IDE/SchemaDesigner/Controller/EnumValues.hs
IHP/IDE/SchemaDesigner/Controller/Enums.hs
IHP/IDE/SchemaDesigner/Controller/Helper.hs
IHP/IDE/SchemaDesigner/Controller/Schema.hs
IHP/IDE/SchemaDesigner/Controller/Tables.hs
IHP/IDE/SchemaDesigner/View/Schema/SchemaUpdateFailed.hs
IHP/IDE/SchemaDesigner/View/Tables/Index.hs
IHP/IDE/ToolServer/Helper/Controller.hs
ihp.cabal
lib/IHP/static/schema-designer.css

Errors from DB Schema Updates are now displayed in a more helpful way

---

IHP/Telemetry.hs
exe/IHP/IDE/DevServer.hs
ihp.cabal
ihp.nix
shell.nix

Implements https://github.com/digitallyinduced/ihp/issues/557

Added Telemetry

---

IHP/IDE/SchemaDesigner/Compiler.hs
IHP/IDE/SchemaDesigner/Controller/Columns.hs
IHP/IDE/SchemaDesigner/Parser.hs
IHP/IDE/SchemaDesigner/Types.hs
IHP/IDE/SchemaDesigner/View/Columns/EditForeignKey.hs
IHP/IDE/SchemaDesigner/View/Columns/NewForeignKey.hs
Test/IDE/SchemaDesigner/CompilerSpec.hs
Test/IDE/SchemaDesigner/ParserSpec.hs

Fixes #372
@Kaeptenblaubaer could you take a look? :)

Adds ON DELETE SET DEFAULT to schema designer

---

Guide/Makefile
Guide/layout.html
Guide/tailwindcss.markdown

You can find my first tailwind app here: https://veghhvypzdbnfpjgomywejhyzagkqmuo.ihpapp.com/NewPost Yes it looks very raw :D 
@kodeFant can you do a review? I've taken some of the code from your gist :)

Added guide on how to use tailwind

---

Guide/your-first-project.markdown

Add a hint that one may need to click Update Db in order to see the insert-statement.

Add a hint that one may need to click Update Db

---

Guide/editors.markdown

Updated the docs on nixpkgs for editor tooling so they are the same as in boilerplate.

updated nixPkgsRev in Editors Tooling 

---

IHP/IDE/CodeGen/ApplicationGenerator.hs

Fix Path To Welcome.hs

---

IHP/ModelSupport.hs
IHP/Prelude.hs

Add function to delete by record ID

---

Guide/auto-refresh.markdown
Guide/controller.markdown
Guide/deployment.markdown
Guide/view.markdown

(was changed for release d02a0699220a87d32889ff2a7b87ad81f8bc8195)

Update docs re change in FrameworkConfig

---

Guide/deployment.markdown
Guide/form.markdown
UPGRADE.md

- nullable selects in forms
- BaseUrl in Config.hs

doc updates

---

IHP/HaskellSupport.hs
IHP/ModelSupport.hs
IHP/ValidationSupport/ValidateField.hs

Fixes https://github.com/digitallyinduced/ihp/issues/596

Support nonEmpty validation also for Id fields

---

Guide/authentication.markdown
IHP/AuthSupport/Controller/Sessions.hs
IHP/Telemetry.hs

Very convenient. Also updated docs.

Made user record updateable in beforeLogin

---

IHP/IDE/CodeGen/JobGenerator.hs

Fixed typo in JobGenerator error message.

---

IHP/Controller/Redirect.hs

Fixes https://github.com/digitallyinduced/ihp/issues/622

Added redirectBack and redirectBackWithFallback

---

CONTRIBUTING.md
Guide/authentication.markdown
Guide/your-first-project.markdown

Reordered some stuff in installation to give a more natural flow.
Added troubleshooting in `CONTRIBUTING.md` for missing packages.

Small doc update for language and troubleshooting

---

Guide/view.markdown

another beforeRender

---

Guide/layout.html
Guide/tailwindcss.markdown

- append to gitignore with newline
- remove inconvenient syntax highlighting for makefiles
- add alternative to run `make tailwind-dev` and `RunDevServer` together

Minor changes to tailwind docs

---

IHP/NameSupport.hs
IHP/SchemaCompiler.hs
Test/Main.hs
Test/NameSupportSpec.hs
Test/SchemaCompilerSpec.hs
shell.nix

Fixes https://github.com/digitallyinduced/ihp/issues/528

Enum values can contain spaces now

---

CONTRIBUTING.md

Make it easier to contribute when many changes are made to IHP before a beta release.

Contributing Changelog Before Next IHP Beta Release

---

Guide/relationships.markdown

Add Example Of Sorting Associated Records

---

IHP/HaskellSupport.hs
Test/HaskellSupportSpec.hs

Fixes https://github.com/digitallyinduced/ihp/issues/658

Adds copyFields function

---

Guide/database.markdown
IHP/QueryBuilder.hs

Hacked this one together thanks to #443, #632, and #434
Fixes #654

Add distinct And distinctOn Functions To QueryBuilder

---

IHP/IDE/SchemaDesigner/View/Columns/Edit.hs
IHP/Telemetry.hs

Two fairly random things to put in the same commit, I know.
The WSL bug: up to now only the older WSL1 was reported, now it reports WSL2 as well. Both are reported as WSL because we really don't care.

categorized columntypes in IDE and fixed bug in telemetry WSL

---

Guide/editors.markdown

https://github.com/digitallyinduced/ihp/issues/406#issuecomment-759301327

Mention Haskell HSX Extension In VS Code Setup

---

CONTRIBUTING.md

Anything else that is necessary for contributing to IHP besides the basics?

Practical Contributing Resources

---

exe/IHP/IDE/DevServer.hs
lib/IHP/Makefile.dist

Ignore Globally Installed Packages When Loading GHCI

---

lib/IHP/Makefile.dist

After I asked about this in the Slack, @s0kil suggested to add it as a make command. I really liked that idea!

Add make command to start (only) postgres server

---

Guide/Makefile
Guide/jobs.markdown
Guide/layout.html

Alternative title: my Sunday afternoon figuring out how jobs work :-) 
I definitely plan on writing about this more in-depth in the future, but for the documentation I just included the basics that I got stuck on as I was trying to figure things out.

Add basic documentation for jobs

---

exe/IHP/IDE/DevServer.hs

Fixes https://github.com/digitallyinduced/ihp/issues/721

Only set ulimit on macOS

---

Guide/layout.html

A proposed minimal solution for getting documentation search quickly up and going. 
Takes the user to DuckDuckGo from the search form and then back to IHP again, so maybe not the smoothest solution compared to something like algolia, but works well and gives pretty good search results until we get something better :)

A minimal DuckDuckGo search bar

---

IHP/FrameworkConfig.hs

I was not correctly lifting the logger into the ConfigBuilder's State monad, causing an `IO Logger` to be registered instead of a Logger. This would cause a crash if the user did not specify a logger.

Fix default logger not being registered correctly

---

IHP/IDE/Data/View/Layout.hs
IHP/IDE/SchemaDesigner/Compiler.hs
IHP/IDE/SchemaDesigner/Parser.hs
IHP/IDE/SchemaDesigner/Types.hs
Test/IDE/SchemaDesigner/CompilerSpec.hs
Test/IDE/SchemaDesigner/ParserSpec.hs

Support Multi-column Indexes

---

Guide/logging.markdown
IHP/FrameworkConfig.hs
IHP/Log/Types.hs

Updated default production log level to "info"

---

Guide/Makefile
Guide/elm.markdown
Guide/layout.html
Guide/purescript.markdown
ProjectGenerator/bin/ihp-new

Try it out: `curl --silent https://raw.githubusercontent.com/digitallyinduced/ihp/sokil/ihp-85-ihp-new---purescript-myproject/ProjectGenerator/bin/ihp-new | bash -s -- --purescript-halogen ihp-purescript-halogen-project`
Closes: #742

Introduce ihp-new --purescript-halogen Flag

---

Guide/Makefile
Guide/layout.html
Guide/websockets.markdown
IHP/ControllerPrelude.hs
IHP/ControllerSupport.hs
IHP/IDE/ToolServer.hs
IHP/RouterSupport.hs
IHP/Server.hs
IHP/WebSocket.hs
lib/IHP/static/ihp-auto-refresh.js

Fixes https://github.com/digitallyinduced/ihp/issues/601

Allow WebSocket controllers to be created from userland

---

IHP/ModelSupport.hs
IHP/SchemaCompiler.hs
Test/SchemaCompilerSpec.hs

Added functionality to the query functions in `IHP/ModelSupport.hs` that measure the time each query takes to execute, and includes this in the logs for each query. Example log for a page in Debug mode:
```
Query (28.136ms): "SELECT COUNT(*) FROM (SELECT bands.* FROM bands) AS _count_values" []
Query (2.628ms): "SELECT COUNT(*) FROM (SELECT performances.* FROM performances) AS _count_values" []
GET /
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Status: 200 OK 0.032103s
```
Also updated the code generation in SchemaCompiler to use the `sqlQuery` function from ModelSupport instead of calling to the Postgres library directly. This way all queries will be logged, not just user created queries.

Add database query time logging

---

IHP/ModelSupport.hs
IHP/SchemaCompiler.hs
Test/ModelSupportSpec.hs

Currently the `didChange` functions returns `True` even when the value is not different from the database value. It was more like a `didTouch` function instead of a `didChange`:
```haskelll
p <- query @Project |> fetchOne -- Project { name = "Test" }
p
|> set #name "Test"
|> didChange #name -- Will return True because the name field has been setted, even though the value is not different
```
This change saves the original database record inside the `MetaBag` to be able to compare the values to only return `True` when there is an actual change.

didChange should not return True when the value is the same as the database value

---

IHP/AutoRefresh.hs
IHP/AutoRefresh/Types.hs
IHP/FrameworkConfig.hs
IHP/IDE/ToolServer.hs
IHP/PGNotify.hs
IHP/Server.hs

Fixes https://github.com/digitallyinduced/ihp/issues/726

Stop Database Connections When Application Stopped.

---

Guide/Makefile
Guide/helpful-tips.markdown
Guide/layout.html

- IHP Flags.
- Using wildcard to infer type constraints, implicit parameters.

Add Helpful Tips To Guide

---

ProjectGenerator/bin/ihp-new

Closes https://github.com/digitallyinduced/ihp/issues/736

Add ihp-new `--version` Flag

---

Guide/authentication.markdown
Guide/form.markdown
IHP/View/CSSFramework.hs
IHP/View/Form.hs
IHP/View/Types.hs
Test/View/CSSFrameworkSpec.hs

Autofocus HTML attribute is a usability improvement for end-users

added support for autofocus

---

CONTRIBUTING.md
Guide/layout.html
Guide/search.js

Based On https://github.com/s0kil/search-ihp-guide

Simple Guide Searching

---

IHP/SchemaCompiler.hs

This is pretty embarrassing, but due to a typo in https://github.com/digitallyinduced/ihp/pull/781, my previous PR didn't really work as advertised... This should fix it [by using the correct pragma](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/exts/pragmas.html#options-ghc-pragma).

Use correct pragma (OPTIONS_GHC instead of GHC_OPTIONS)!

---

IHP/IDE/Types.hs
exe/IHP/IDE/DevServer.hs

Implements And Closes https://github.com/digitallyinduced/ihp/issues/770

Debounce File Changes

---

IHP/IDE/CodeGen/JobGenerator.hs
Test/IDE/CodeGeneration/JobGenerator.hs

Fix issue 774

---

IHP/WebSocket.hs

Added modelContext constraint to WSApp

---

Guide/database.markdown

Fix typo/mistake

---

IHP/Assets/ControllerFunctions.hs
IHP/Assets/Types.hs
IHP/Assets/ViewFunctions.hs
IHP/ControllerPrelude.hs
IHP/ControllerSupport.hs
IHP/ViewPrelude.hs
ihp.cabal

Fixes https://github.com/digitallyinduced/ihp/issues/829

cache busting

---

Guide/your-first-project.markdown

Note:
* correct 'open New Table' dialog: the corresponding image seems out of date (as viewed on Firefox/Linux)

docs(guide): update "Your first project" 

---

Guide/editors.markdown
Guide/helpful-tips.markdown
Guide/layout.html

Added documentation on special haskell syntax

---

IHP/Controller/Param.hs
IHP/SchemaCompiler.hs
Test/Controller/ParamSpec.hs
Test/SchemaCompilerSpec.hs

Fixes https://github.com/digitallyinduced/ihp/issues/855

Fixed auto generated ParamReader instances missing implementation for readParameterJSON

---

Guide/hsx.markdown
IHP/HtmlSupport/Parser.hs
IHP/HtmlSupport/QQ.hs
Test/HtmlSupport/QQSpec.hs

Fixes https://github.com/digitallyinduced/ihp/issues/741

HSX: boolean data-attributes now use true/false values instead of behaving like HTML boolean attributes

---

IHP/FrameworkConfig.hs
IHP/Log.hs

ran quick test [here](https://github.com/Montmorency/ihp-prmod) on logging. Still need to update docs though. Maybe a breaking change so need to edit Upgrade and perform a few more tests.

switching makeRequestLogger in Log.hs from unsafePerformIO to liftIO

---

lib/IHP/static/helpers.js

Fixed turbolink redirect not working as expected after form submission. Fixes #822

---

IHP/Controller/Redirect.hs

Fixes https://github.com/digitallyinduced/ihp/issues/880

Export Redirect Back Functions

---

IHP/IDE/Data/View/ShowDatabase.hs

Link To Show Table In Schema

---

Guide/hsx.markdown
IHP/AutoRefresh/View.hs
IHP/ErrorController.hs
IHP/Fetch.hs
IHP/HSX/Parser.hs
IHP/HSX/QQ.hs
IHP/HSX/ToHtml.hs
IHP/Modal/ViewFunctions.hs
IHP/QueryBuilder.hs
IHP/View/CSSFramework.hs
IHP/View/Form.hs
IHP/ViewPrelude.hs
IHP/ViewSupport.hs
Test/HSX/ParserSpec.hs
Test/HSX/QQSpec.hs
Test/Main.hs
ihp.cabal

Fixes https://github.com/digitallyinduced/ihp/issues/851

Rename IHP.HtmlSupport Modules To IHP.HSX

---

Guide/search.js

Pin Search Widget Assets To Specific Version, And Use Faster CDN

Fix Guide Search

---

IHP/Controller/Redirect.hs

Fixes https://github.com/digitallyinduced/ihp/issues/787

Fix redirectBackWithFallback To Handle URLs and Paths

---

IHP/ValidationSupport.hs
IHP/ValidationSupport/ValidateField.hs
IHP/ValidationSupport/ValidateIsUnique.hs
Test/ValidationSupport/ValidateFieldSpec.hs

Fixes https://github.com/digitallyinduced/ihp/issues/899

Introduce isTrue and isFalse in IHP.ValidationSupport

---

IHP/IDE/Data/Controller.hs
IHP/IDE/Data/View/ShowDatabase.hs
IHP/IDE/ToolServer/Types.hs

Fixes https://github.com/digitallyinduced/ihp/issues/765

Delete All Rows Menu Option

---

Guide/Makefile
Guide/file-storage.markdown
Guide/layout.html
IHP/ControllerPrelude.hs
IHP/FileStorage/Config.hs
IHP/FileStorage/ControllerFunctions.hs
IHP/FileStorage/Preprocessor/ImageMagick.hs
IHP/FileStorage/Types.hs
ihp.cabal
ihp.nix
shell.nix

With the file storage module we can easily manage files stored inside S3 and similiar cloud storage services

Added new file storage module

---

CONTRIBUTING.md
Guide/editors.markdown
lib/IHP/Makefile.dist

Fixes https://github.com/digitallyinduced/ihp/issues/776

Rename make ghci To make console

---

Guide/validation.markdown
IHP/ValidationSupport/ValidateIsUnique.hs

Fixes https://github.com/digitallyinduced/ihp/issues/764
Maybe there is a better way, open to ideas.

Introduce withCustomErrorMessageIO

---

Guide/querybuilder.markdown
Guide/validation.markdown
IHP/AuthSupport/Controller/Sessions.hs
IHP/QueryBuilder.hs
IHP/ValidationSupport/ValidateIsUnique.hs
Test/QueryBuilderSpec.hs

Adds `filterWhereCaseInsensitive`, `validateIsUniqueCaseInsensitive` and switches the IHP built-in login controller to use a case-insensitive email check

Case insensitive

---

IHP/IDE/SchemaDesigner/Compiler.hs
IHP/IDE/SchemaDesigner/Controller/Columns.hs
IHP/IDE/SchemaDesigner/Parser.hs
IHP/IDE/SchemaDesigner/Types.hs
IHP/IDE/SchemaDesigner/View/Layout.hs
Test/IDE/SchemaDesigner/CompilerSpec.hs
Test/IDE/SchemaDesigner/ParserSpec.hs
lib/IHP/static/IDE/schema-designer.css

Also fixed that the schema designer only shows one index in the GUI

Fixed schema parser unable to deal with expressions inside a CREATE INDEX statement

---

IHP/SchemaCompiler.hs
Test/SchemaCompilerSpec.hs

This code was already there for INSERT statement, so I just copied it for UPDATE statements as well :smiley: 
Closes #913

Explicit type cast for UPDATE statements for array types

---

CONTRIBUTING.md

Add tip about what to do if you get the error message `*** WARNING: . is writable by someone else, IGNORING! Suggested fix: execute 'chmod go-w .'`
Related gitter convo: https://gitter.im/digitallyinduced/ihp?at=60c38450c705e53c1c87baef

Update contributing troubleshooting section

---

IHP/IDE/CodeGen/Controller.hs

Fix issue https://github.com/digitallyinduced/ihp/issues/920

 Use applicationName When Generating Action And Mail

---

IHP/FrameworkConfig.hs
IHP/Server.hs
ihp.cabal
ihp.nix
shell.nix

Fixes https://github.com/digitallyinduced/ihp/issues/931

Added support for specifying a CORS policy

---

Guide/authentication.markdown

I'm not sure what's best to put here. But the action as it is will cause a runtime error.

Add path to redirect to after user is created

---

Guide/recipes.markdown

Another (hopefully) helpfull recipe.

Add filesystem example to recipes which can also be used to deliver a custom 404 page

---

Guide/database.markdown
IHP/IDE/SchemaDesigner/Compiler.hs
IHP/IDE/SchemaDesigner/Parser.hs
IHP/IDE/SchemaDesigner/Types.hs
IHP/IDE/SchemaDesigner/View/Columns/Edit.hs
IHP/ModelSupport.hs
IHP/Postgres/Inet.hs
IHP/Postgres/Point.hs
IHP/Postgres/TSVector.hs
IHP/Postgres/TypeInfo.hs
IHP/SchemaCompiler.hs
IHP/View/Form.hs
Test/Main.hs
Test/Postgres/Point.hs
Test/Postgres/Support.hs
Test/Postgres/TSVector.hs
ihp.cabal

Closes https://github.com/digitallyinduced/ihp/issues/286
Supersedes https://github.com/digitallyinduced/ihp/pull/344

Postgres tsvector Support

---

Guide/recipes.markdown

fetchOneOrNothing is the better choice here

replace fetch by fetchOneOrNothing in IHP/Guide/recipes.markdown

---

Guide/relationships.markdown

Fixes https://github.com/digitallyinduced/ihp/issues/950

Added docs on fetching all Comments with their Posts (Many-to-one)

---

Guide/form.markdown

Fix small typo in guide

---

IHP/IDE/SchemaDesigner/Compiler.hs
IHP/IDE/SchemaDesigner/Controller/Columns.hs
IHP/IDE/SchemaDesigner/Parser.hs
IHP/IDE/SchemaDesigner/Types.hs
IHP/IDE/SchemaDesigner/View/Layout.hs
Test/IDE/SchemaDesigner/CompilerSpec.hs
Test/IDE/SchemaDesigner/ParserSpec.hs

Fixes https://github.com/digitallyinduced/ihp/issues/961
https://www.postgresql.org/docs/current/indexes-unique.html

Support CREATE UNIQUE INDEX

---

IHP/Controller/Session.hs
IHP/FlashMessages/ControllerFunctions.hs
IHP/LoginSupport/Helper/Controller.hs
Test/Controller/SessionSpec.hs
Test/Main.hs

The session storage module has been redesigned. Also added tests for SessionValue instances. Unfortunately, I was unable to set up a test environment to store sessions. Therefore, the tests were run in the application and are not present in the testing unit.
Issue: https://github.com/digitallyinduced/ihp/issues/371

[#371]Session values

---

IHP/IDE/SchemaDesigner/Controller/Validation.hs
lib/IHP/static/IDE/ihp-schemadesigner.js

The name is now also checked against the keyword list in singularized form.
Also fixed an undefined error in the js error hint

Fixed modules not being a restricted keyword. Fixes #993

---

IHP/IDE/SchemaDesigner/Controller/Columns.hs

The delete problem was caused by two issues:
1. the deleteTableIndex function that wanted to delete the index statement had a pattern match failure:
deleteTableIndex indexName list = filter (\index -> get #indexName index /= indexName) list
The call to get #indexName index fails for e.g. CreateTable statements
2. When deleting a column the schema designer wanted to always delete the first index on the table, even if the index has nothing to do with the column that is being deleted. This is fixed now.

Fixed deleting a column when the table has an index fails. Fixes #984

---

Guide/file-storage.markdown
IHP/FileStorage/ControllerFunctions.hs

Fixes https://github.com/digitallyinduced/ihp/issues/997
Also fixed some spelling errors in Storage Guide

Export uploadToStorage Function

---

Guide/controller.markdown
IHP/ControllerSupport.hs

Closes https://github.com/digitallyinduced/ihp/issues/273

Allow Setting Headers Per Request

---

IHP/IDE/SchemaDesigner/Compiler.hs
IHP/IDE/SchemaDesigner/Parser.hs
IHP/IDE/SchemaDesigner/Types.hs
IHP/SchemaCompiler.hs
Test/IDE/SchemaDesigner/CompilerSpec.hs
Test/IDE/SchemaDesigner/ParserSpec.hs
Test/SchemaCompilerSpec.hs

Fixes https://github.com/digitallyinduced/ihp/issues/1007

Added support for double default values and sql type casts

---

IHP/ErrorController.hs

Very small fix for a spelling error I noticed when debugging #1010.

small spelling fix

---

IHP/Controller/Param.hs
IHP/ModelSupport.hs
IHP/SchemaCompiler.hs
Test/Controller/ParamSpec.hs
Test/ModelSupportSpec.hs

Fixes #1017 
I've added no tests, but there were no tests for this to begin with.

Fix NUMERIC support (map to Data.Scientific)

---

IHP/IDE/StatusServer.hs
lib/IHP/static/livereload.js

Fix issue https://github.com/digitallyinduced/ihp/issues/998

Livereload morphdom Patch Head

---

IHP/Controller/Param.hs
Test/Controller/ParamSpec.hs

Fixes https://github.com/digitallyinduced/ihp/issues/894

Made param error messages more human friendly

---

IHP/IDE/SchemaDesigner/Compiler.hs
IHP/IDE/SchemaDesigner/Parser.hs
IHP/IDE/SchemaDesigner/Types.hs
Test/IDE/SchemaDesigner/CompilerSpec.hs
Test/IDE/SchemaDesigner/ParserSpec.hs

Fixes https://github.com/digitallyinduced/ihp/issues/964

Support where clauses in CREATE INDEX statements

---

Guide/your-first-project.markdown

It doesn't cause errors to have it in there, but it seems like a good idea to have beginners practice this.

Add step to remove `<th></th>`

---

Guide/helpful-tips.markdown

Specify Web/Types.hs to distinguish from build/Generated/Types.hs

Specify Web/Types.hs

---

IHP/IDE/Data/Controller.hs

This addresses issue https://github.com/digitallyinduced/ihp/issues/1042

Fix bug regarding order of fields in data editor

---

IHP/ModelSupport.hs

https://www.dictionary.com/e/its-vs-its/

Fix typo (it's -> its)

---

IHP/ValidationSupport/ValidateField.hs

use like 
```haskell
buildPost post = post
|> fill @'["year"]
|> validateField #year (matchesRegex "^[0-9]{4}$")
```
(bad example regex, please don't use in production ;))

add `matchesRegex` validator

---

IHP/QueryBuilder.hs

See https://stackoverflow.com/questions/69011689/define-a-querybuilder-by-filtering-then-sorting

Fixed queryOr causing strange type errors in complex Queries.

---

Guide/relationships.markdown

Add note about multiple nested resources

---

Guide/relationships.markdown

https://github.com/digitallyinduced/ihp/pull/1101 follow up
(and some trailing spaces cleanup)

More multiple Include docs

---

IHP/View/Types.hs

Edited from https://github.com/digitallyinduced/ihp/pull/1157#discussion_r732235585

Explain the reason for passing a second `CSSFramework`

---

Guide/tailwindcss.markdown

https://github.com/digitallyinduced/ihp/pull/1194#issuecomment-963873666

Fix failing docs

---

exe/IHP/IDE/DevServer.hs

@amitaibu can you give this a try? :)

Delay app start until postgres is ready. Fixes #1210

---

Guide/purescript.markdown

I had run into a few issues trying to get my app deployed on IHP Cloud. These are the steps that I took to get it deploying and running properly.

Add troubleshooting steps for Purescript on IHP Cloud

---

Guide/tailwindcss.markdown

Removed the wording of old information.
Probably forgotten to erase in #1194.

delete the wording of old information

---

lib/IHP/static/helpers.js

fixes https://github.com/digitallyinduced/ihp/issues/1232
fixes https://github.com/digitallyinduced/ihp/issues/1233

Prevent changing URL on form with error

---

IHP/ApplicationContext.hs
IHP/DataSync/ChangeNotifications.hs
IHP/DataSync/Controller.hs
IHP/DataSync/Types.hs
IHP/PGListener.hs
IHP/Server.hs
ihp.cabal

Fixes the issue that DataSync uses too many database connection (one for each DataSubscription) when working with multiple users.

Added PGListener module

---

lib/IHP/DataSync/ihp-datasync.js

This will ease debugging when something goes wrong

Validate input arguments passed to functions of the public DataSync api

---

IHP/SchemaCompiler.hs
Test/SchemaCompilerSpec.hs

Replaced 'RETURNING *' used in sql queries with a specific column list

---

IHP/IDE/SchemaDesigner/Compiler.hs
IHP/IDE/SchemaDesigner/Parser.hs
Test/IDE/SchemaDesigner/CompilerSpec.hs
Test/IDE/SchemaDesigner/ParserSpec.hs

Fixed parsing of unquoted extension names in CREATE EXTENSION sql statements.

---

.github/workflows/build.yml
.github/workflows/docs.yml
.github/workflows/ihp-new.yml
.github/workflows/pr_compile_check.yml
.github/workflows/tests.yml
NixSupport/make-nixpkgs-from-options.nix

Fixes https://github.com/digitallyinduced/ihp/issues/1268

Updated nixpkgs to get latest HLS version

---

IHP/IDE/CodeGen/MigrationGenerator.hs
IHP/IDE/SchemaDesigner/Compiler.hs
IHP/IDE/SchemaDesigner/Parser.hs
IHP/IDE/SchemaDesigner/Types.hs
Test/IDE/CodeGeneration/MigrationGenerator.hs
Test/IDE/SchemaDesigner/CompilerSpec.hs
Test/IDE/SchemaDesigner/ParserSpec.hs

My attempt at addressing #1275.
I tested in ghci:
```
:l Test/IDE/CodeGeneration/MigrationGenerator.hs
hspec tests
```

Handle default value changes in migrations

---

IHP/IDE/CodeGen/MigrationGenerator.hs
IHP/IDE/SchemaDesigner/Compiler.hs
IHP/IDE/SchemaDesigner/Parser.hs
IHP/IDE/SchemaDesigner/Types.hs
Test/IDE/CodeGeneration/MigrationGenerator.hs
Test/IDE/SchemaDesigner/CompilerSpec.hs
Test/IDE/SchemaDesigner/ParserSpec.hs

Handle dropping default values in migrations

---

Guide/helpful-tips.markdown
Guide/ihp-pro.markdown
Guide/mail.markdown
Guide/recipes.markdown
IHP/Mail.hs
README.md

Small doc fixes

---

IHP/IDE/Data/Controller.hs

@Montmorency this should fix the issue below. Can you review?

Fixed data editor errors when trying to edit the schema_migrations table

---

IHP/FrameworkConfig.hs
IHP/Server.hs
IHP/Test/Mocking.hs

Fixes https://github.com/digitallyinduced/ihp/issues/1318 and https://ihp.digitallyinduced.com/community/ShowThread?threadId=349f909a-4b99-4448-b5f9-cfaefbca9aea

Fixed test runs not closing log file handles

---

IHP/Breadcrumb/ViewFunctions.hs
Test/RouterSupportSpec.hs

fixes https://github.com/digitallyinduced/ihp/issues/1335

Correct type signature of `breadcrumbLink`

---

IHP/PGListener.hs
Test/Main.hs
Test/PGListenerSpec.hs

Specifically the unsubscribe test proofs that the current implementation of unsubscribe is broken

Added tests for PGListener subscribe and unsubscribe

---

IHP/DataSync/Controller.hs
IHP/DataSync/Types.hs

We switched from manual resource handling to Exception.bracket with MVars to make sure that all data subscriptions are always closed when the underlying websocket connection is closed

Fixed data subscriptions not always closed in specific cases

---

Guide/examples.markdown

windofchange has been migrated to Next.js

Update examples.markdown: remove windofchange

---

lib/IHP/DataSync/ihp-querybuilder.js
lib/IHP/DataSync/ihp-querybuilder.test.js

datasync select columns

---

IHP/ModelSupport.hs

What do you think, @mpscholten?
I'll have to either use this, or catch the exception - which definitely isn't as nice looking, or understandable. Alternatively, I could change the SQL, but it would get overly complex as well.

add sqlQueryScalarMaybe

---

lib/IHP/static/helpers.js

Fixes https://github.com/digitallyinduced/ihp/issues/1385

Update Browser Location With Form Response URL

---

IHP/RouterSupport.hs
Test/RouterSupportSpec.hs

Fixes https://github.com/digitallyinduced/ihp/issues/1387

Router Support [UUID]

---

IHP/HaskellSupport.hs

Fixes https://github.com/digitallyinduced/ihp/issues/1383

Implement "|>>" Operator

---

IHP/RouterSupport.hs
Test/RouterSupportSpec.hs

Continues https://github.com/digitallyinduced/ihp/pull/1388

pathTo support [UUID]

---

IHP/DataSync/Controller.hs
IHP/DataSync/DynamicQuery.hs
IHP/DataSync/REST/Controller.hs
IHP/DataSync/REST/Routes.hs
IHP/DataSync/REST/Types.hs
IHP/DataSync/Types.hs
IHP/GraphQL/Compiler.hs
IHP/GraphQL/JSON.hs
IHP/GraphQL/Parser.hs
IHP/GraphQL/SchemaCompiler.hs
IHP/GraphQL/ToText.hs
IHP/GraphQL/Types.hs
Test/GraphQL/CompilerSpec.hs
Test/GraphQL/ParserSpec.hs
Test/GraphQL/SchemaCompilerSpec.hs
Test/Main.hs
Test/Postgres/Support.hs
ihp.cabal
lib/IHP/DataSync/graphql.js
lib/IHP/DataSync/react.js

Includes a parser for a small subset of GraphQL and a tiny incomplete compiler that contains the gist of the overall thing.
The GraphQL queries can be called from DataSync like this:
```javascript
function HelloWorld() {
// const tasks = useQuery(query('tasks'));
const tasks = useGraphQLQuery("{ tasks { id title } }")
return <div>
{JSON.stringify(tasks)}
</div>
}
```

GraphQL Support

---

NixSupport/make-nixpkgs-from-options.nix

Fix based on https://gist.github.com/Gabriel439/61be09ed5c223c17e5a9268323afa223
You can try it with this in `default.nix`:
```nix
let
ihp = builtins.fetchGit {
url = "https://github.com/digitallyinduced/ihp.git";
rev = "71c4966967fe0743d5bbace1a31d32a651fd4f12";
allRefs = true;
};
```

Fixed build of ormolu on M1 computers

---

IHP/IDE/CodeGen/MigrationGenerator.hs
IHP/IDE/SchemaDesigner/Compiler.hs
IHP/IDE/SchemaDesigner/Parser.hs
IHP/IDE/SchemaDesigner/SchemaOperations.hs
IHP/IDE/SchemaDesigner/Types.hs
Test/IDE/SchemaDesigner/CompilerSpec.hs
Test/IDE/SchemaDesigner/ParserSpec.hs
Test/IDE/SchemaDesigner/SchemaOperationsSpec.hs

and all other permutations of those last parameters

support ALTER TABLE .. ADD CONSTRAINT .. DEFERRABLE INITIALLY DEFERRED

---

lib/IHP/static/IDE/inter.css

Succeeds https://github.com/digitallyinduced/ihp/pull/1396

Fix DevServer Fonts Path

---

IHP/IDE/CodeGen/MigrationGenerator.hs
IHP/IDE/SchemaDesigner/Compiler.hs
IHP/IDE/SchemaDesigner/Controller/Columns.hs
IHP/IDE/SchemaDesigner/Parser.hs
IHP/IDE/SchemaDesigner/SchemaOperations.hs
IHP/IDE/SchemaDesigner/Types.hs
IHP/IDE/SchemaDesigner/View/Layout.hs
Test/IDE/SchemaDesigner/CompilerSpec.hs
Test/IDE/SchemaDesigner/ParserSpec.hs

Fixes https://github.com/digitallyinduced/ihp/issues/1384

Schema Support PostgreSQL Index Column Ordering

---

lib/IHP/DataSync/ihp-datasync.js
lib/IHP/DataSync/ihp-querybuilder.js
lib/IHP/DataSync/package-lock.json
lib/IHP/DataSync/package.json
lib/IHP/DataSync/react.js

The latency from the US to the IHP Backend server is just too much for me

implemented a simple draft of how optimistic operations could look like in DataSync

---

Guide/file-storage.markdown
IHP/ControllerPrelude.hs

Closes https://github.com/digitallyinduced/ihp/issues/1426

Export all FileInfo accessors

---

IHP/LoginSupport/Helper/View.hs

Fixes https://github.com/digitallyinduced/ihp/issues/1419

Add currentUserId To IHP.LoginSupport.Helper.View

---

IHP/AuthSupport/Controller/Sessions.hs

Fixes https://github.com/digitallyinduced/ihp/issues/1418
Also added `beforeLogout`
And renamed `maxFailedLoginAttemps` to `maxFailedLoginAttempts`

Add afterLogoutRedirectPath To SessionsControllerConfig

---

Guide/file-storage.markdown
IHP/FileStorage/Config.hs

Closes https://github.com/digitallyinduced/ihp/issues/1428

Filebase Storage Support

---

IHP/ControllerSupport.hs

E.g. to be able to call `ensureIsUser` for the full application

Support sending a response from initContext

---

lib/IHP/static/vendor/ihp-ssc.js

Reasonable fix for https://github.com/digitallyinduced/ihp/issues/1440

Allow To Toggle SSC Debug Mode

---

IHP/FileStorage/ControllerFunctions.hs

Closes https://github.com/digitallyinduced/ihp/issues/1425

Throw Exceptions When Trying To Save A File

---

Guide/your-first-project.markdown

At least I assume this is why this wasn’t working for me.

make dumpdb, not make db

---

.github/workflows/build.yml
Guide/config.markdown
NixSupport/haskell-packages/hs-brotli.nix
NixSupport/haskell-packages/wai-middleware-brotli.nix

I thought to extract into its own library, but turns out to be less complicated for end user if we include the Brotli libraries in IHP.

Compression Middleware Guide

---

README.md

Updated link to newsletter

---

Guide/file-storage.markdown

The parameters to this function have been updated.

Update applyImageMagick parameters

---

IHP/RouterSupport.hs
NixSupport/haskell-packages/ihp-hsx.nix
Test/HSX/ParserSpec.hs
ihp-hsx/IHP/HSX/HaskellParser.hs
ihp-hsx/IHP/HSX/HsExpToTH.hs
ihp-hsx/IHP/HSX/Parser.hs
ihp-hsx/IHP/HSX/QQ.hs
ihp-hsx/ihp-hsx.cabal
ihp-hsx/shell.nix

This allows support for dot notation in HSX expressions

Use GHC's parser for Haskell expressions in HSX

---

Guide/authentication.markdown
Guide/authorization.markdown
Guide/controller.markdown
Guide/database.markdown
Guide/file-storage.markdown
Guide/form.markdown
Guide/helpful-tips.markdown
Guide/hsx.markdown
Guide/jobs.markdown
Guide/mail.markdown
Guide/oauth.markdown
Guide/querybuilder.markdown
Guide/realtime-spas.markdown
Guide/recipes.markdown
Guide/relationships.markdown
Guide/scripts.markdown
Guide/seo.markdown
Guide/stripe.markdown
Guide/testing.markdown
Guide/validation.markdown
Guide/view.markdown
Guide/websockets.markdown
Guide/your-first-project.markdown

Dot notation docs

---

IHP/LoginSupport/Helper/Controller.hs

Fixes https://github.com/digitallyinduced/ihp/issues/1490

Ensure is admin refactor

---

IHP/IDE/StatusServer.hs
IHP/IDE/Types.hs
IHP/SchemaCompiler.hs
exe/IHP/IDE/DevServer.hs

Improve error report when when parsing the Schema.sql fails

---

Guide/editors.markdown
Guide/installation.markdown

Make editor docs more visible

---

Guide/hsx.markdown
IHP/ViewPrelude.hs
Test/HSX/QQSpec.hs
ihp-hsx/IHP/HSX/ConvertibleStrings.hs
ihp-hsx/IHP/HSX/QQ.hs

Improved support for preEscapedTextValue

---

Guide/scripts.markdown

Might be useful to have some documentation on running IHP Scripts from within ghci.

adding some docs on using scripts from ghci.

---

IHP/FrameworkConfig.hs
IHP/IDE/SchemaDesigner/Compiler.hs
IHP/IDE/SchemaDesigner/Controller/Helper.hs
IHP/IDE/SchemaDesigner/Controller/Indexes.hs
IHP/IDE/SchemaDesigner/Parser.hs
IHP/IDE/SchemaDesigner/SchemaOperations.hs
IHP/IDE/SchemaDesigner/View/Indexes/Edit.hs
IHP/IDE/SchemaDesigner/View/Layout.hs
IHP/IDE/ToolServer.hs
IHP/IDE/ToolServer/Routes.hs
IHP/IDE/ToolServer/Types.hs
ihp-hsx/IHP/HSX/QQ.hs
ihp.cabal

Add, edit and delete for indexes

---

.github/workflows/build.yml

Fakedata useful library for generating test data.

Adding fakedata to cachix

---

NixSupport/default.nix

Allow building an IHP app without postgres and HLS included

---

NixSupport/haskell-packages/ihp-hsx.nix
ihp.cabal
lib/IHP/Makefile.dist

Disabled split-sections

---

lib/IHP/static/vendor/ihp-ssc.js

See https://github.com/digitallyinduced/ihp/issues/1560

Fix change the class attributes on input or textarea elements in SSC component actions

---

lib/IHP/DataSync/ihp-datasync.js

Fixes https://github.com/digitallyinduced/ihp/issues/1575

Fixed problem with calling crypto.randomUUID on older browsers

---

Guide/deployment.markdown

Shipnix deployment and migration instructions in IHP Guide

Shipnix deployment instructions

---

IHP/AutoRefresh.hs
IHP/WebSocket.hs

Problem:
> Are there some known cases where websockets time-out and die after a while of idle time?
Having this issue with AutoRefresh now (v1.0). A fresh browser session, and it seems to work all nicely, but during a longer process it seems to reliably not work. Difficult to debug!
13 Antworten
Reproducable via https://github.com/kodeFant/dying-autorefresh

Fixed GC Issue in AutoRefresh

---

Guide/installation.markdown

Resolves https://github.com/digitallyinduced/ihp/issues/1602.
Link to Codespaces IHP config: https://github.com/rvarun11/codespaces-ihp

documentation: Add GitHub Codespaces in Guide

---

Guide/deployment.markdown

Too detailed? Too little detail? Wrong section?

Documentation for GHCRTS

---

lib/IHP/static/vendor/ihp-ssc.js

fixed replacing text nodes bug

---

NixSupport/README.md

Right now it will redirect there anyway - but probably a nice courtesy to not use her deadname

Update README.md url to use updated github username

---

ihp-hsx/IHP/HSX/Parser.hs

Added kind attribute to HSX attribute whitelist

---

IHP/IDE/CodeGen/MigrationGenerator.hs
IHP/IDE/SchemaDesigner/Compiler.hs
IHP/IDE/SchemaDesigner/Parser.hs
IHP/IDE/SchemaDesigner/Types.hs
Test/IDE/CodeGeneration/MigrationGenerator.hs

Fix trigger issue

---

Guide/authentication.markdown
Guide/auto-refresh.markdown
Guide/deployment.markdown
Guide/examples.markdown
Guide/purescript.markdown
Guide/tailwindcss.markdown
Guide/your-first-project.markdown
IHP/AuthSupport/Controller/Sessions.hs
IHP/FrameworkConfig.hs
IHP/Mail/Types.hs

Removed mentions of IHP Cloud

---

IHP/IDE/CodeGen/MigrationGenerator.hs
Test/IDE/CodeGeneration/MigrationGenerator.hs

Fixed trigger function for updated_at always recreated

---

.ghci
IHP/SchemaCompiler.hs
Test/SchemaCompilerSpec.hs

Fixes https://github.com/digitallyinduced/ihp/issues/1641

Code Generator now splits Generated.Types into multiple modules 

---

IHP/IDE/Postgres.hs
IHP/IDE/Types.hs
NixSupport/default.nix
NixSupport/devenv.nix
NixSupport/make-nixpkgs-from-options.nix
NixSupport/mkGhcCompiler.nix
exe/IHP/IDE/DevServer.hs
ihp.nix

Hello all! 👋 
I've recently started working with IHP and since I'm rather familiar with nix I wanted to tackle the devenv.sh integration work, so this PR adds a module that can be used to setup IHP project with devenv effortlessly as suggested in #1572.
Setting up an IHP project to use devenv is as simple initialising devenv with `devenv init` and adding the module to `devenv.nix`:
```nix
{ pkgs, inputs, config, ... }:
{
imports = [
"${inputs.ihp}/NixSupport/devenv.nix"
];
packages = [ ];
ihp.enable = true;
ihp.projectPath = ./.;
}
```
Once devenv finishes building everything, the development server can be run with the `start` script or the by starting devenv processes with `devenv up`.
The module does the heavy lifting of setting up the GHC compiler along with the required packages while …

feat: add devenv support

---

IHP/View/Form.hs

also in formForWithoutJavascript; and actually set formAction as promised by the paragraph above

Actually use formForWithOptions in its doc example

---

Guide/config.markdown
Guide/package-management.markdown

Updates docs for devenv + nix flakes

Updated package management docs for nix flakes / devenv

---

UPGRADE.md

Package name is devenv

---

Troubleshoot/ihp-troubleshoot

Add check for Nix version to troubleshoot script

---

Guide/form.markdown

`selectLabel` can be used on the Show as well

---

Guide/recipes.markdown
IHP/AuthSupport/Authorization.hs

My brain can't work with the double negative of `accessDeniedUnless`. It's much easier for me to say when to  access deny.

Add `accessDeniedWhen`

---

Guide/database.markdown

The example was provided by @s0kil , thanks :sunglasses:

Add example for fetching a single column with sqlQuery

---

IHP/RouterSupport.hs

Fixes https://github.com/digitallyinduced/ihp/issues/1743

Replace the redundant Data controller constraint on parseRoute with Typeable controller

---

CONTRIBUTING.md

https://github.com/digitallyinduced/ihp/issues/1747#issuecomment-1637028354

Mention `direnv allow` in Contributing guide

---

Guide/file-storage.markdown

I've implemented it in a project, and I think it can be useful for others
Here's how it looks:
[2023-07-25-15-15-57.webm](https://github.com/digitallyinduced/ihp/assets/125707/ce042baa-80eb-4a63-8853-499f2c4bbbc0)

Guide on how to remove an uploaded image

---

.ghci
IHP/AuthSupport/Controller/Sessions.hs
IHP/DataSync/Controller.hs
IHP/DataSync/ControllerImpl.hs
IHP/DataSync/Role.hs
IHP/DataSync/RowLevelSecurity.hs
IHP/HaskellSupport.hs
IHP/IDE/CodeGen/MigrationGenerator.hs
IHP/IDE/SchemaDesigner/View/Layout.hs
IHP/IDE/ToolServer/Layout.hs
IHP/Job/Dashboard.hs
IHP/LoginSupport/Helper/Controller.hs
IHP/RouterSupport.hs
IHP/Server.hs
IHP/ServerSideComponent/ControllerFunctions.hs
IHP/ServerSideComponent/HtmlDiff.hs
IHP/Test/Mocking.hs
IHP/ValidationSupport/ValidateCanView.hs
Paths_ihp.hs
exe/IHP/CLI/NewMigration.hs
ihp.cabal

Fixes https://github.com/digitallyinduced/ihp/issues/1640

Fix all GHC warnings

---

Guide/file-storage.markdown

Uncheck the "Remove file" checkbox, in case it was previously checked.

Improve file upload example

---

Guide/your-first-project.markdown

Closes https://github.com/digitallyinduced/ihp/issues/1808

Make the Your First Project guide consistent with Nix files

---

CONTRIBUTING.md

Fixes https://github.com/digitallyinduced/ihp/issues/1813

Updated contribute docs to reflect latest dev changes

---

Guide/config.markdown

Import module to use `env`

---

Guide/elm.markdown

Update link to Elm articles

---

IHP/ValidationSupport/ValidateField.hs

Use a more robust check for `isUrl` validator

---

ihp.cabal

Follow up https://github.com/digitallyinduced/ihp/pull/1882
@mpscholten Fixes the build error

Fix comment on ihp.cabal

---

Guide/mail.markdown

Minor, I'll self merge when green

Fix action name in Mail example

---

Guide/view.markdown

Docs about Passing JSON to the View

---

Guide/logging.markdown
IHP/Controller/Context.hs

Fix example of overriding Logger

---

IHP/ModelSupport.hs
IHP/Prelude.hs
IHP/SchemaCompiler.hs
Test/SchemaCompilerSpec.hs

```haskell
-- Prev
when someCondition do
updateRecord myRecord
pure ()
-- New
when someCondition do
updateRecordDiscardResult myRecord
```

Added updateRecordDiscardResult

---

Guide/jobs.markdown

Follow up to https://github.com/digitallyinduced/ihp/pull/1956

Backoff Strategy docs

---

IHP/FrameworkConfig.hs

Possible fix for https://github.com/digitallyinduced/ihp/issues/1959

Set db connection pool max connections to aleast the value of getNumCapabilities

---

NixSupport/nixosModules/appWithPostgres.nix

We want the project `flake.nix` to configure this

Don't set system.stateVersion

---

NixSupport/ghc-12264.patch
NixSupport/mkGhcCompiler.nix

https://gitlab.haskell.org/ghc/ghc/-/merge_requests/12264?commit_id=ef323487c2a6bdc15dea6f7777e18eb32203c2a0
Ben provided a patch file for using that linker speedup on GHC 9.8.2 👍

Added backport for GHC patch #12264

---

Guide/testing.markdown

Update cachix and direnv related dependencies

Update GH Action docs

---

IHP/QueryBuilder.hs

Fixes https://github.com/digitallyinduced/ihp/issues/1867

queryUnionList

---

NixSupport/nixosModules/options.nix

fixes https://github.com/digitallyinduced/ihp/issues/1979

Remove `numa` from RTS flags

---

lib/IHP/static/helpers.js

#1824 
This change will add all submitted checkboxes as query params on form submit

Fix multiple checkboxes submit

---

IHP/NameSupport.hs
Test/IDE/CodeGeneration/ViewGenerator.hs
Test/NameSupportSpec.hs
ihp-ide/IHP/IDE/CodeGen/ViewGenerator.hs

Add capitalisation to view generator

---

Guide/database.markdown

minor nits I noticed while working through the docs and trying to onboard.

update two small grammatical errors in the docs

---

ihp-ide/IHP/IDE/SchemaDesigner/View/Layout.hs

fix: remove Just wrapper from foreign key OnDelete display

---

Guide/deployment.markdown

Follow up to https://github.com/digitallyinduced/ihp/pull/2027

Docs on `systemd` integration

---

Guide/testing.markdown

And link to the GH action on the boilerplate repo

Remove `nix-shell` from testing instructions

---

IHP/Controller/Render.hs

Even when running on the latest master  that has [print exceptions to log](https://github.com/digitallyinduced/ihp/pull/2038), looking at logs - connected to AWS CloudWatch - we don't see that extra info.
Marc wrote:
```haskell
let devHandlers =
[ postgresHandler
, paramNotFoundExceptionHandler
, patternMatchFailureHandler
, recordNotFoundExceptionHandlerDev
]
-- Prod handlers should not leak any information about the system
let prodHandlers =
[ recordNotFoundExceptionHandlerProd
]
let allHandlers = if ?context.frameworkConfig.environment == Environment.Development
then devHandlers
else prodHandlers
```
so in prodMode (which your app likely is running in), only the recordNotFoundExceptionHandlerProd handler is available. And that handler always returns a 404 status code. Your logs …

Force evaluation of blaze HTML also on `ProdMode`

---

IHP/ErrorController.hs

fixes #2051
| Dev | Production |
| -- | -- |
| ![image](https://github.com/user-attachments/assets/1d8a92bb-9570-4aca-8487-ff6a75c3c476) | ![image](https://github.com/user-attachments/assets/520b0c9c-cacd-42e0-b056-9275bb9be3d1) |

Show routing error only on DEV mode

---

IHP/FileStorage/ControllerFunctions.hs
Test/FileStorage/ControllerFunctionsSpec.hs

Fix createTemporaryDownloadUrlFromPath missing a slash

---

Guide/editors.markdown

make it clearer that lsp(-ui) is an *alternative* to eglot
drop commented-out "flycheck but it does not work" bit and keep configs in the use-package blocks they belong in, and don't fail if smartparens/ligature/rainbow packages are not installed (they are not builtin)
drop reference to someone's long init-file
(though would like to know why it was there cf.
https://github.com/digitallyinduced/ihp/pull/1872#issuecomment-2878942116 )
note difference between M-x eglot and eglot-ensure hook

Clean up emacs docs a bit

---

IHP/Test/Mocking.hs

@andreytroeglazov this should fix the error with the test suite 👍

testing: call approotMiddleware

---

IHP/Environment.hs
IHP/FrameworkConfig.hs

I was wondering what differences switching between the environments lead to, and ended up grepping the ihp repo. Maybe this helps others.

Document Environment and the default differences between Prod/Dev
