digitallyinduced/ihp

- IHP/IDE/StatusServer.hs
While the app is compiled, localhost:8000 shows a misleading <title> tag ("Compilation Error")
> make <title> match <h1>

- Guide/routing.markdown
- IHP/RouterSupport.hs
Spotted in our of our error logs that HEAD requests are failing right now.
These are already basically supported, we just disallowed them in the routing with AutoRoute.
> Add support for HEAD requests

- lib/IHP/Makefile.dist
This fixes a bug where the `.envrc` keeps growing every time you regenerate it.
By default, nix-shell gets the current $PATH and prepends the nix store $PATH. That means that if you already have the current `.envrc` loaded, both the current content of `.envrc` and the new computed path will be save to `.envrc`, making it grow over time. This is fixed by calling nix-shell with `--pure`.
> Run nix-shell with --pure when creating the .envrc

- Guide/your-first-project.markdown
corrected wrong url in "Adding Validation" section
from ```/Posts/new``` to ```/NewPost``` as the former does not work, at least at this point in the guide.
> Correct wrong url in Adding Validation section

- Guide/installation.markdown
Nix install URL `https://nixos.org/nix/install` uses a redirect, `-L` flag needs to specified to `curl`, otherwise empty response is returned:
```
$ curl https://nixos.org/nix/install -v
*   Trying 68.183.215.91:443...
* TCP_NODELAY set
* Connected to nixos.org (68.183.215.91) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec …
```
> Fix curl command in Installation Guide

- Guide/architecture.markdown
corrected a few typos from `to much` to `too much` and from `few javascript` to `little javascript`
> Corrected a few typos in architecture.markdown

- IHP/IDE/ToolServer.hs
- IHP/Server.hs
Apparently there was a segfault on Linux earlier, so a memory cache was used for the session store on Linux. This causes frequent logouts though, so I removed it. No segfaults so far. If they happen again, let's fix the root cause :-)
> use session store, even on Linux

- IHP/SchemaCompiler.hs
> Fixed SchemaCompiler only accepting null values written `null`, and not `NULL`

- Guide/form.markdown
- IHP/View/Form.hs
Previously:
```
{(textField #title) { fieldInput = (\fieldInput -> H.input ! A.required "required") }}
```
Now:
```
{(textField #title) { required = True } }
```
Fixes https://github.com/digitallyinduced/ihp/issues/165
> Make it easier to mark form fields as required

- IHP/IDE/SchemaDesigner/Compiler.hs
- IHP/IDE/SchemaDesigner/Controller/Columns.hs
- IHP/IDE/SchemaDesigner/Controller/Helper.hs
- IHP/IDE/SchemaDesigner/Controller/Tables.hs
- IHP/IDE/SchemaDesigner/Parser.hs
- IHP/IDE/SchemaDesigner/Types.hs
- IHP/IDE/SchemaDesigner/View/Columns/Edit.hs
- IHP/SchemaCompiler.hs
- Test/IDE/SchemaDesigner/CompilerSpec.hs
- Test/IDE/SchemaDesigner/ParserSpec.hs
Sql Types previously have been stored as just a Text. Now we have a new data structure PostgresType instead of the Text value. This will make it easier to support types like `Numeric (p, s)` in the future.
Additionally the sql parser now can parse a lot more types. Completly new are:
- Bigint
- Real
Missing aliases for already existing type have been added as well:
- FLOAT8 (= DOUBLE PRECISION)
- INT4 (=INT)
- INTEGER (=INT)
- BOOL (=BOOLEAN)
- TIMESTAMPZ (=TIMESTAMP WITH TIME ZONE)
Previously the sql types had to be written in upper case form, so `boolean` was disallowed while `BOOLEAN` was ok. This has been fixed and now both forms will be parsed as expected.
> Improved sql parser

- IHP/IDE/DevServer.hs
- IHP/IDE/ToolServer.hs
- IHP/Server.hs
Additonally this improves the performance on VMs a lot when loading IHP as a source module.
Especially fixes the issue with clientsession (#182).
> Disabled external interpreter to avoid issues on certain Linux systems

- Guide/routing.markdown
- IHP/RouterPrelude.hs
- IHP/RouterSupport.hs
Fixes #213 
The "old" `getInput` has been renamed to `takeByteString` in the latest attoparsec version. We also usually want the result as a `Text` value, therefore a new `remainingText` has been added :)
> Added remainingText function which replaces the old getInput

- IHP/Controller/Param.hs
Nothing will only be returned after the read is attempted, which will continue to allow empty stringy types to parse successfully as `Just ""`
> Accept empty strings in optional parameter parsers, returning Nothing

- Guide/view.markdown
- Guide/your-first-project.markdown
- IHP/View/TimeAgo.hs
- lib/IHP/static/helpers.js
It looks like 'Uhr' abbreviated suffix is hard coded into the date-time JavaScript helper.
> Fix date-times to correctly show abbreviated timezone suffix.

- lib/IHP/static/helpers.js
Right now when a server errors is caused by a form submission, the error is just logged via `console.log()`. But the browser will not show the actual error message. With this change the actual error response will be shown.
Fixes https://github.com/digitallyinduced/ihp/issues/206
> Show html response when the form submission triggers an error

- lib/IHP/Makefile.dist
$PATH might contain spaces and other special characters. We need to quote them else the script will fail.
> Use "prinf %q" instead of "echo" in Makefile.dist

- build-haddock
> Fixed quickjump index not build by haddock causing quickjump to fail in api docs

- Guide/architecture.markdown
- Guide/authentication.markdown
- Guide/controller.markdown
- Guide/database.markdown
- Guide/form.markdown
- Guide/hsx.markdown
- Guide/index.markdown
- Guide/installation.markdown
- Guide/naming-conventions.markdown
- Guide/querybuilder.markdown
- Guide/recipes.markdown
- Guide/relationships.markdown
- Guide/routing.markdown
- Guide/scripts.markdown
- Guide/session.markdown
- Guide/validation.markdown
- Guide/view.markdown
- Guide/your-first-project.markdown
The guide is an excellently-written piece of documentation, and should show other Haskell projects how documentation really can complement well-typed code. There are some small typos and grammatical errors, however, that I have fixed in this commit.
I hope this is useful and not too nit-picky, and will contribute to the overall polish of the project.
> Typos, grammar and readability in the Guide

- CONTRIBUTING.md
Not sure if this is the intended process, but it was what I had to do to get GHCI loading Main correctly.
> 'make' only shows help; 'make all' needed to create lib directory to ensure GHCI loads Main correctly

- IHP/IDE/SchemaDesigner/View/Layout.hs
- lib/IHP/static/schema-designer.css
This small update removes the create buttons which are redundant because the primary way should be the context menu. When the schema is fully empty, the notice to use the right click menu is shown at the center of the screen. This PR also fixes the margin of the "Update DB" button :) 
Fixes https://github.com/digitallyinduced/ihp/issues/147 and https://app.clubhouse.io/digitallyinduced/story/1620/schemadesigner-kontextmen%C3%BC-verbessern-bzw-duplicate-buttons-entfernen
> Removed redundant buttons from schema designer to simplify

- IHP/AuthSupport/Controller/Sessions.hs
- IHP/Controller/FileUpload.hs
- IHP/Controller/Param.hs
- IHP/LoginSupport/Middleware.hs
- IHP/ModelSupport.hs
- IHP/QueryBuilder.hs
- IHP/RouterSupport.hs
- IHP/SchemaCompiler.hs
UUIDs are still the default and recommended way for the id column. For cases where UUIDs don't work, you can now change the column type to SERIAL or BIGSERIAL to work with integers.
Fixes https://github.com/digitallyinduced/ihp/issues/302
> Added support for SERIAL primary keys

- IHP/Controller/Param.hs
- IHP/ModelSupport.hs
This enables float values to be used everywhere where double values previously were possible already
> Added ParamReader Float and InputValue Float instances

- IHP/FrameworkConfig.hs
Fixes https://github.com/digitallyinduced/ihp/issues/331 by looking for `build/ihp-lib` before looking up the lib dir via `RunDevServer`
> Improved findLibDir to search in build/ihp-lib. Fixes #331

- lib/IHP/IHPSchema.sql
- lib/IHP/Makefile.dist
Fixes https://github.com/digitallyinduced/ihp/issues/333
This fixes the above issue by introducing a new `IHPSchema.sql` which is loaded before the app specific `Schema.sql`. This way we can be sure the extension is set.
After the new IHP version with this is released, [we can remove the uuid setup code from the boilerplate](https://github.com/digitallyinduced/ihp-boilerplate/blob/master/Application/Schema.sql#L1).
> Moved uuid-ossp extension setup to IHP from the app specific Schema.sql

- IHP/IDE/ToolServer.hs
- IHP/ModelSupport.hs
- IHP/QueryBuilder.hs
- IHP/SchemaCompiler.hs
- IHP/ScriptSupport.hs
- IHP/Server.hs
Previous all sql queries have been printed to stdout all the time. This change adds a new option queryDebuggingEnabled to the modelContext. Depending on this setting queries will be logged. By default this will be set to True in dev mode, and to False in Production mode
Fixes https://github.com/digitallyinduced/ihp/issues/358
> Only log sql queries in development mode

- IHP/ValidationSupport/ValidateField.hs
- Test/ValidationSupport/ValidateFieldSpec.hs
Although their usage are prohibited by ICANN for the wider internet, dotless email addresses are perfectly valid as per the standards. I included a warning leading to the announcement made in 2013 by ICANN regarding the usage of dotless email addresses.
references:
* https://en.wikipedia.org/wiki/Email_address#Examples
* https://www.icann.org/news/announcement-2013-08-30-en
> Allow dotless email addresses in `isEmail`

- IHP/Controller/Param.hs
- IHP/ErrorController.hs
This PR improves the error message when a call to param fails. The new error screen looks like this:
> Improved error message when 'param ".."' is called and the param is not found

- IHP/ErrorController.hs
- IHP/ModelSupport.hs
- IHP/Prelude.hs
- IHP/QueryBuilder.hs
This error just hit me again while working on a project. This PR makes errors by `fetchOne` more friendly by explicitly telling the sql query that caused the failure.
Fixes long outstanding: https://app.clubhouse.io/digitallyinduced/story/728/fehlermeldung-verbessern-cannot-find-model
> `fetchOne` error improvement

- Guide/controller.markdown
- IHP/Controller/Param.hs
Thanks for working on IHP!
It seems like perhaps the default value used to come after the parameter name and the docs still have this old flipped order.
> Fix paramOrDefault documentation

- lib/IHP/static/helpers.js
Hi! I'd like to propose this fix for https://github.com/digitallyinduced/ihp/issues/390, an issue I encountered when using dateTime in a 12-hour locale. This change will produce canonical time stamps with hours, minutes, and without seconds, for both 12- and 24-hour locales.
> update dateTime so that it works correctly for 12-hour locales

- IHP/IDE/CodeGen/ApplicationGenerator.hs
By importing that module by default, developers can easily use types like the User when rendering the Layout view.
> codegen: import Generated.Types in layout view

- IHP/ControllerSupport.hs
- IHP/ErrorController.hs
- IHP/FrameworkConfig.hs
- IHP/RouterSupport.hs
We don't want to display all the fancy error messages which sometimes include sql queries for normal users.
> Disable all fancy debugging error handlers in production

- exe/IHP/CLI/run-script
This was caused by a recent change to more modules requiring a FrameworkConfig constraint. Fixes #421
> Fixed scripts not running in dev mode

- IHP/FetchRelated.hs
Currently collectionFetchRelated only worked when the referenced field was a foreign key. Now this also works for query builders.
This fixes #207
> Added support for collectionFetchRelated to work with query builders

- Guide/database.markdown
- IHP/QueryBuilder.hs
The OFFSET clause is useful for implementing paging of large datasets. It is most often used together with the LIMIT clause.
> Adding support for Postgres OFFSET clause

- Guide/your-first-project.markdown
There was a discussion in the gitter about how the name PostsController can be confusing, especially in the context of routing. I added a small note to elaborate the difference
> guide: Address confusion with PostsController / HTTP POST

- IHP/ControllerPrelude.hs
- IHP/ModelSupport.hs
The type Only is not available in controllers. Strange as there is an example in the documentation showing use of it, but it does not actually compile. Fixed with this PR.
> Re-exporting Only from postgresql-simple

- CONTRIBUTING.md
- IHP/IDE/SchemaDesigner/View/Columns/Edit.hs
- IHP/ModelSupport.hs
- IHP/SchemaCompiler.hs
There was some support already (seemed to be started but not finished) in the code generator. In addition to adding support for localtime this PR also solves an unrelated bug: editing a primary key (.e.g. setting unique on/off) always deselects it as a primary key. Also added a couple of clarifications to contributing doc.
> Add support for timestamp without time zone (i.e. localtime)

- IHP/IDE/Data/Controller.hs
- IHP/IDE/Data/View/EditValue.hs
- IHP/IDE/SchemaDesigner/Controller/Columns.hs
- IHP/IDE/SchemaDesigner/View/Columns/Edit.hs
- IHP/IDE/SchemaDesigner/View/Columns/New.hs
- lib/IHP/static/ihp-schemadesigner.js
Postgres Array types have been supported in Schema.sql and codegen for a few weeks now, but there hasn't been any support in the IDE. I also lumped in a bugfix for the duplicate null/NULL occasionally showing in the default dropdown.
> IDE support for array types

- Troubleshoot/ihp-troubleshoot
When developing on IHP itself the link will be a relative path starting with `../`, making the script think it's broken. Using the `-f` flag on readlink we get an absolute path which works in all cases.
> troubleshoot script: use absolute path when verifying link

- Guide/database.markdown
- Guide/deployment.markdown
Expanded on the current docs to help people move their projects forward through database changes. Chose steps that points contributors to how we should automate this in the IDE, using DDL which avoids manually updating Fixtures.sql, is a lot less involved, and now can be done without errors in the IDE. The "old way" is still there as an alternate route.
> Database refactoring docs

- IHP/AuthSupport/Controller/Sessions.hs
- IHP/FetchRelated.hs
- IHP/HaskellSupport.hs
- IHP/LoginSupport/Middleware.hs
- IHP/ModelSupport.hs
- IHP/QueryBuilder.hs
- IHP/SchemaCompiler.hs
- IHP/ValidationSupport/ValidateIsUnique.hs
This solves a problem where tables with self referencing has many relations could not be used with IHP due to a infinite self reference at the type level
Previously:
```haskell
let queryBuilder :: QueryBuilder User = query @User
```
Now:
```haskell
let queryBuilder :: QueryBuilder "users" = query @User
```
Fixes https://github.com/digitallyinduced/ihp/issues/501
Fixes https://github.com/digitallyinduced/ihp/issues/321
> The type variable of `QueryBuilder typeVar` now is the table name instead of the model type

- Guide/authentication.markdown
- IHP/Controller/Session.hs
- ihp.cabal
Adds http basic authentication support (including docs). Also removes some duplicate entries in the cabal file.
Solves issue #96
> basicAuth support

- lib/IHP/static/helpers.js
Adds support for data-confirmtext="Your custom are you sure text here" on any link having class js-delete.
The standard text bugs me for two reasons:
1) too generic (warning should confirm exactly what is about to be deleted)
2) language is english. While users will tolerate english error messages, messages in ordinary usage should be localized.
If the approach taken here is accepted (add a comment), I will also update the docs with this feature in a separate commit (same PR)
> support for custom text on js-delete

- Guide/view.markdown
This is how I read the code anyway.
Btw, is there any reason `data-turbolinks-preload` isn't in use? turbolinksInstantClick.js has
```
const preloadAttribute = function(link) {
return true;
…
}
```
It'd be nice if we could have preloading unless that attribute is explicitly false, but perhaps there's a good reason for the early `return true` there?
> Doc how to (not) preload links

- IHP/Controller/FileUpload.hs
- IHP/Controller/Param.hs
- IHP/Controller/RequestContext.hs
- IHP/ControllerSupport.hs
- IHP/HaskellSupport.hs
- Test/Controller/ParamSpec.hs
- Test/Main.hs
- ihp.cabal
The functions fill and param (and related) now work with JSON requests. Previously they only worked with urlencoded form request bodies. For this to work, the request needs to have Content-Type: application/json
> Added support for JSON request bodies

- Guide/view.markdown
- lib/IHP/static/vendor/turbolinksInstantClick.js
(But still preload if that attribute does not exist at all!)
See #536. Just removing the `return true` would turn off preloading if
the attribute wasn't there at all – pretty sure we don't want
that. Now it should only turn off preloading if it's explicitly there
and false.
> Respect `data-turbolinks-preload='false'` attribute

- IHP/IDE/CodeGen/Controller.hs
- IHP/IDE/CodeGen/View/Generators.hs
- IHP/IDE/CodeGen/View/NewMigration.hs
- IHP/IDE/ToolServer/Types.hs
- IHP/ModelSupport.hs
- IHP/SchemaMigration.hs
- exe/IHP/CLI/Migrate.hs
- exe/IHP/CLI/NewMigration.hs
- ihp.cabal
- lib/IHP/static/ihp-codegen.css
Adds a migration system for production schema changes.
Generate a migration from the web or CLI:
```bash
new-migration create-projects
```
Creates a file at `Application/Migration/1604854836-create-projects.sql`. The migration sql code can be placed in there.
In production you need to run `migrate` from the project directory. This will run all migrations that haven't been executed yet. The `migrate` tool also generates a `schema_migrations` table to keep track of which migrations have been executed already.
> Migration System

- Guide/installation.markdown
- Guide/recipes.markdown
- IHP/Controller/Param.hs
- IHP/IDE/SchemaDesigner/View/Columns/Edit.hs
- Test/Controller/ParamSpec.hs
- lib/IHP/static/ihp-schemadesigner.js
- FIX: numberField with negative number gives `ParamReader Int: Failed reading: takeWhile1` because `readParam Int` does not allow minus sign.
- ADD: JSONB column was missing from IDE (but otherwise supported).
- FIX: Timezone without timezone field did not have NOW() available as default in IDE
- FIX: Spawning browser on `./start`does not work in windows due to missing package in install guide.
- Added hint of nix gc in install docs. Saves people many GB.
> Signed Int readParam bugfix, added JSONB column in IDE and two other minor fixes

- IHP/IDE/SchemaDesigner/View/Columns/Edit.hs
- IHP/IDE/SchemaDesigner/View/Columns/New.hs
- IHP/IDE/SchemaDesigner/View/Layout.hs
- lib/IHP/static/ihp-schemadesigner.js
This PR has 2 commits,
Commit 1:
Bugfix: Consider Haskell keywords as illegal keywords as well.
Commit 2:
Change suggested column name from `*reserved keyword_` to `*singular table name*_*reserved keyword*`
> Bug fix + different message suggestion for column name

- Guide/Makefile
- Guide/layout.html
- Guide/testing.markdown
- IHP/Test/Mocking.hs
- ihp.cabal
Is this useful to incorporate into IHP framework? Is this the right spot for it?
Example usage:
```
import Test.Controller.Mocking
spec :: Spec
spec = beforeAll (configBuilder >>= mockContext >>= \c -> withContext c (pure ()) do
describe "Run mock test" do
it "checks headers" $ c -> withParams [("param","val"] c do
heads <- headers (mockAction SomeAction)
let loc = lookup "Location" heads
loc `shouldNotBe` Nothing
it "checks status" $ c -> withParams [("param","val"] c do
mockActionStatus AnotherAction `shouldReturn` status200
```
> Add mocking framework for controllers

- CONTRIBUTING.md
- Guide/mail.markdown
- IHP/Mail.hs
- IHP/Mail/Types.hs
- IHP/SchemaCompiler.hs
- ihp.cabal
- ihp.nix
- shell.nix
> Added support for SendGrid and standard SMTP

- IHP/IDE/SchemaDesigner/View/Schema/Error.hs
When some error is raised after reading the schema file, the header (toggle and update db buttons) are duplicated,  because that HTML is in the [`schemaDesignerLayout`](https://github.com/digitallyinduced/ihp/blob/master/IHP/IDE/SchemaDesigner/View/Layout.hs#L12:L29) function, resulting in something like this:
I made the less changes possible to keep the `bg-white visual-error` div inside a `container`.
> Remove code already present in schemaDesignerLayout

- IHP/IDE/Data/Controller.hs
Not 100% where `parseValues` is used, so this might be completely wrong.
Fixes https://github.com/digitallyinduced/ihp/issues/642 (partially)
> Escape single quotes

- IHP/View/CSSFramework.hs
Teal is no longer in the default colour scheme of **tailwindcss** v2 (@kodeFant thanks for the tip!) so I'm using green instead.
I also made the styling of `SuccessFlashMessage` otherwise identical to `ErrorFlashMessage`.
> Make tailwindcss styled flash messages consistent

- CONTRIBUTING.md
- IHP/Controller/Param.hs
- IHP/ModelSupport.hs
- IHP/Prelude.hs
- Test/Controller/ParamSpec.hs
While LocalTime was supported in the IDE for DB columns, it was not supported in the input fields.
Since localtime vs utc is just a flag in postgresql (just different field types, identical storage) no time zones are involved. It is just a matter of interpretation (local time or utc). Hence, we don't need any change in settings in the flatpickr and we happily parse Z(ulu) just as for UTCTime.
> support LocalTime for dateField and dateTimeField

- Troubleshoot/README.md
- build-haddock
When running `./build-haddock` it fails due to some Haskell packages not being loaded, so now we run it inside a `nix-shell`.
> Fix Haddock Script

- Guide/authentication.markdown
- IHP/ControllerPrelude.hs
- IHP/LoginSupport/Helper/Controller.hs
- IHP/LoginSupport/Types.hs
- IHP/ViewPrelude.hs
Auth helpers like `currentUser` are now part of the `IHP.ControllerPrelude` and `IHP.ViewPrelude` modules and so don't need to be added to the `Application.Helper.View` and `Application.Helper.Controller` files anymore
The `CurrentUserRecord` is now specified in `Web.Types` which fixes #641
> Auth updates

- IHP/QueryBuilder.hs
`#fullName` should map to `full_name` in the database.
> Fix distinctOn QueryBuilder Function

- IHP/QueryBuilder.hs
Add the functions `filterWhereLike` and `filterWhereMatches` for `WHERE a LIKE b` and `WHERE a ~ b` queries respectively. There are also case-insensitive versions of these functions.
> Add query builders for LIKE and ~ queries

- ihp.cabal
- ihp.nix
- lib/IHP/Makefile.dist
Intended to be merged back into https://github.com/digitallyinduced/ihp/pull/688
~~It seems flags defined in `*.cabal` [default to true](https://cabal.readthedocs.io/en/3.4/setup-commands.html#controlling-flag-assignments), so I've added `-FastBuild` to explicitly define it to false.~~
Also added the `-flate-specialise` flag
~~Since the flags default to true, now it makes more sense to have `OptimizedBuild` instead of `FastBuild`.~~
> Faster Builds

- Guide/troubleshooting.markdown
- Troubleshoot/README.md
- Troubleshoot/ihp-troubleshoot
In preparation for https://github.com/digitallyinduced/ihp/issues/689, I've wanted to make it easier working with the script as it becomes more complex. If a user has bash installed, they most likely also have python.
Also removed this:
```bash
step "Checking Cachix"
if [ -d "$HOME/.config/cachix" ]; then
ok "Cachix config exists"
else
fail "Cachix config is missing. Is cachix installed?"
fi
```
When installing `cachix`, it does not create a `~/.config/cachix` directory.
Fixes #689, with https://github.com/digitallyinduced/ihp/issues/689#issuecomment-761710557
> Refactor Troubleshooting Script

- IHP/HtmlSupport/Parser.hs
I added all the elements that weren't already in the `parents` list from the link below. I wasn't sure whether to name a new list and/or sort alphabetically, but hopefully it at least checks out functionally.
Element index [reference](https://www.w3.org/TR/SVG2/eltindex.html)
W3C Candidate Recommendation
Appendix F: Element Index
> Add support for SVG elements in hsx

- IHP/HtmlSupport/Parser.hs
- Test/HtmlSupport/ParserSpec.hs
Some people structure their HTML code in a way that introduces spaces in
the closing tags. This is valid HTML, but the hsx parser will
complain when copying the HTML into hsx.
The following should be valid hsx after this change:
```html
<span>
<i class="fab fa-html5"></i
>
</span>
<span>
<i class="fab fa-html5"></i >
</span>
```
> Allow hsx to parse spaces in closing tags

- IDE/IHP/IDE/CodeGen/Controller.hs
Simply adds `paramOrDefault` for `applicationName` parameter.
Closes #710
> Fixes Job generator always generating to Web

- lib/IHP/Makefile.dist
`make -B build/ihp-lib` failed with "missing delimiter`on line 110. Fixed.
> spaces in Makefile.dist gives missing delimiter error on build

- IHP/Controller/Redirect.hs
- lib/IHP/static/helpers.js
This addition has been discussed in slack a few times.
To keep the footprint small (it is a workaround, after all), I have added just one method instead of the full redirectX-set.
This workaround is mostly useful just for actions and paths anyway.
Very useful when you need it.
> forceRedirectToPath

- IDE/IHP/IDE/SchemaDesigner/Parser.hs
- Test/IDE/SchemaDesigner/ParserSpec.hs
- run-tests
Keep getting parser errors for SQL formatted as:
```sql
CREATE TYPE Stuff AS ENUM (
'One',
'Two',
'Three',
'Four',
'Five',
'Six',
'Seven',
'Eight',
'Nine',
'Ten'
);
```
Currently IHP only allowed:
```sql
CREATE TYPE Stuff AS ENUM (
'One',
'Two',
'Three',
'Four',
'Five',
'Six',
'Seven',
'Eight',
'Nine',
'Ten');
```
> Flexible Whitespace In Enum Definition

- IHP/HtmlSupport/Parser.hs
This allows the use of the htmx [class-tools](https://htmx.org/extensions/class-tools/) Extension.
> Whitelist the classes attribute

- IHP/SchemaCompiler.hs
When setting -Wall in .ghci, I get a bunch of warnings in build/Generated/Types.hs which essentially can't be suppressed since they're constantly re-generated. This adds a GHC_OPTIONS pragma to suppress them.
As a side note, I also get the following warning; is this intentional, or should `hiding (Field)` be removed?
```
build/Generated/Types.hs:16:1: warning: [-Wdodgy-imports]
Module ‘Database.PostgreSQL.Simple.ToField’ does not export ‘Field’
|
16 | import Database.PostgreSQL.Simple.ToField hiding (Field)
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
> Add GHC_OPTIONS to supress some -Wall warnings for generated file

- Guide/layout.html
- Guide/search.js
Did not take into account the `/Guide/` path, so now the search is more resilient.
> Fix Search On Production Website

- build-haddock
Maybe we need a single file with all GHC options. Or maybe GHC supports a variable we could set, something like `export GHC_OPTIONS=''` and all instance of GHC will use it.
> Ignore Global Packages When Running Haddock

- Guide/authentication.markdown
The code/markup under "Trying out the login" was broken.
`<a href="{NewSessionAction}">Login</a>` results in a verbatim route `./{NewSessionAction}`.
`<a href={NewSessionAction}>Login</a>` results in the intended route `/NewSession`.
> Remove breaking quotation marks

- IHP/SchemaCompiler.hs
I was debugging IHP for some other reason, when I realized my earlier "fix" (https://github.com/digitallyinduced/ihp/pull/797) didn't fully fix the issue. I've made sure this time that this actually gets the warnings removed...
> remove bad commas from OPTIONS_GHC pragma

- NixSupport/default.nix
One pain point I've had developing with IHP is that I would often need to google various functions to look up their type signature. Having a Hoogle instance that's built along with IHP will make it much easier for discovering functions and type signatures (especially so since IHP provides a custom Prelude).
I can imagine enabling this by default and putting a link in the dev server UI, but one drawback to this would be increased build time. I imagine cachix alleviates this to some extent, but I don't think there's no getting around `make -B .envrc` taking a bit longer when adding custom Haskell packages. What do the devs think?
> Add  Hoogle(/Haddock) support

- IHP/IDE/SchemaDesigner/Controller/EnumValues.hs
- Test/IDE/SchemaDesigner/Controller/EnumValuesSpec.hs
- Test/Main.hs
This change ensures that enum values created or updated via EnumValuesController are both non-empty and unique. 
Fixes #782
> Unique enum values

- IHP/LoginSupport/Helper/View.hs
Previously didn't have LoginSupport View helper equivalent for `currentAdminOrNothing` and `currentAdmin`. This is just boilerplate that would otherwise be added in the application level. Only requires import `CurrentAdminRecord` type family and exporting the helper functions.
Non-breaking change. 
Tested by creating small IHP application with Admin Authentication and expected View rendering on Admin Sessions.
> LoginSupport Helper View

- Guide/jobs.markdown
- IHP/Server.hs
Fixes #816 
some development code made its way through to master -- I comment out background workers when running in ghci since when running the server in ghci with background workers you're unable to CTRL-C to stop execution for some reason
> Uncomment background workers

- Guide/routing.markdown
- IHP/ModelSupport.hs
- IHP/RouterSupport.hs
- Test/RouterSupportSpec.hs
Currently AutoRoute can't handle non-UUID ID types. This introduces the ability for custom ID parsing through Type Application, and changes AutoRoute to be a wrapper around a new function
```haskell
autoRouteWithIdType :: (?context :: RequestContext, Data idType) => (ByteString -> Maybe idType) -> Parser controller
```
This allows for passing in a function which can convert to another ID type, such as the included `parseIntegerId`
```haskell
parseIntegerId :: (Data idType) => ByteString -> Maybe idType
parseIntegerId queryVal = let
rawValue :: Maybe Integer = readMay (cs queryVal :: String)
in
rawValue >>= Just . unsafeCoerce
```
Users need to manually tell AutoRoute which custom Id type in needs to parse in the instance declaration:
```haskell
instance AutoRoute TestController where …
```
> Add support for Integer ID types

- Guide/installation.markdown
Link to [current `nix.trustedUsers` documentation](https://search.nixos.org/options?show=nix.trustedUsers&query=nix.trustedUsers) instead of to a hard-coded revision of the source code of it.
> Link to current nix.trustedUsers docs

- Guide/tailwindcss.markdown
I think the docs forgot to mention that a few extra lines could be removed when replacing bootstrap with tailwind.
The bootstrap js files and popper dependency can also be removed
> Update docs for "Removing Bootstrap"

- IHP/Modal/ViewFunctions.hs
- lib/IHP/Makefile.dist
This doesn't really do real minification like renaming variable names to one letter, but it removes all spaces/tabs/new lines, and is pretty good.
Taken from here: https://mohammadthalif.wordpress.com/2016/07/25/how-to-minify-css-using-simple-bash-commands/
> Minify Production CSS

- Guide/jobs.markdown
- IHP/Controller/Render.hs
- IHP/HtmlSupport/Parser.hs
- IHP/Job/Dashboard.hs
- IHP/Job/Dashboard/Auth.hs
- IHP/Job/Dashboard/Types.hs
- IHP/Job/Dashboard/Utils.hs
- IHP/Job/Dashboard/View.hs
- IHP/Job/Types.hs
- ihp.cabal
Jobs share lots in common. By default, in order to provide an interface for viewing and running jobs, IHP users would have to create separate controllers, views, and actions for each job type individually  which is error prone and just not fun. The goal of this job dashboard to use leverage Haskell's type programming and the similar type characteristics of jobs to produce a customizable dashboard for interacting with an IHP application's jobs.
In the future I could imagine this being extended to allow for scheduling of jobs and other nice features.
See included documentation for details https://github.com/digitallyinduced/ihp/pull/832/files#diff-b046ff406e82435d7978bf6566eab8772b94e3b8092a3d8c389d173a0ebfbe9dR94
TODO
> Jobs dashboard

- lib/IHP/Makefile.dist
Currently the non moving gc causes server crashes in production, https://github.com/digitallyinduced/ihp/issues/799
> Disable nonmoving-gc as a possible solution to #799

- IHP/IDE/ToolServer/Layout.hs
Very small PR. To route to autogenerated Apps like ADMIN (localhost:8000/admin/). Previously link broken ((localhost:8000/admin) in IDE without a trailing slash, similar for other autogenerated applications.
> Added Trailing slash for additional apps in IDE

- IHP/QueryBuilder.hs
Apparently the compile equations for MatchesOp were missing, so I added them.
> compile equations for MatchesOp added.

- IHP/QueryBuilder.hs
Just a small follow-up to #889: I noticed that, on most of the *JoinedTable functions, I had forgotten to add the constraint `IsJoined model joinRegister` to the context. This reduced type safety by allowing to add filtering by values of columns that belong to tables that have not been joined.
> Added missing IsJoined-Constraints

- ProjectGenerator/default.nix
Turned ProjectGenerator/default.nix into a function by adding a param "pkgs" that defaults to <nixpkgs>
If nothing is passed in this should behave the same, but now the file can be imported  using the nix builtin "import".
> ProjectGenerator: Make <nixpkgs> a param.

- IHP/Fetch.hs
- IHP/ModelSupport.hs
- IHP/QueryBuilder.hs
- Test/QueryBuilderSpec.hs
I added a function labelResults to the QueryBuilder interface that allows for labelling the results of a query with the values of corresponding values of a joined table. This can be used, for instance, to query all comments and obtain them labeled with the ids of the posts they belong to.
```haskell
labeledComments <-
query @Comment
|> innerJoin @Post (#postId, #id)
|> labelResults @Post #id
|> fetch
```
This piece of code will provide in labeledComments a list of type [LabeledData (Id' "posts") Comment]. With filters or comprehension, the comments can thus be sorted accordings to the posts they belong to.
This approach would seem to be much more flexible than the current approach using fetchRelated. For instance, it works seamlessly with many-to-one relations:
```haskell
labeledComments …
```
> Labeled Query Results

- Guide/database.markdown
- IHP/IDE/Data/Controller.hs
- IHP/IDE/Data/View/ShowQuery.hs
- lib/IHP/static/IDE/ihp-schemadesigner.js
Two small changes I feel like might be nice:
- The SQL query written in the Ace input now persists between pages and won't reset after hitting `Enter`
- SQL errors are shown inline in a bootstrap alert box (see screenshot below) instead of going to a different page
> Show SQL errors inline instead of separate crash page

- lib/IHP/static/vendor/ihp-ssc.js
Bug case: Testing the Counter Example in the IHP docs Server-Side Components using Firefox
1. If you click the increment button, both the input value and the text will change.
2. If you change the input value directly, both the input value and the text will change.
3. If you after these steps click the increment button again, the input value will not change accordingly
`domNode.setAttribute` does not update the input element after it has been dirtied. We must therefore mutate the `domNode.value` to make it work.
Not sure if this will also apply to other form tags as well, will probably do some more testing on this another day :)
> Makes sure to alway update input and textarea in Server-Side Components

- Guide/tailwindcss.markdown
In the new versions, Tailwind complains and does not accept the build script unless it's provided with the `-i` flag before the input  argument.
Also added the `--minify` flag for the production build for a bit smaller css bundle.
> Fix Tailwind script that fails in new versions

- IHP/View/TimeAgo.hs
- lib/IHP/static/helpers.js
I wanted to add a function that displays only the time. This addresses issue #979.
Here's an example of how it looks:
I'm not sure about the naming of the function `time`. This is probably too generic, right?
> Implement time function in TimeAgo

- IHP/IDE/SchemaDesigner/View/Layout.hs
- LICENSE-3RD-PARTY
- lib/IHP/static/IDE/schema-designer.css
This fixes #955 and adds some icons from the pgadmin4 project to the schema editor:
I originally added some code to order the DDL statements, e.g. first tables, then indices, then enums etc. But I removed that change since I usually have my DDL statements in an order that makes sense to me (regarding ordering, also have a look at #584). That's also why I changed the code to include comments as well. Thoughs?
> Show icons in Schema Editor, fix #955

- Guide/view.markdown
This MR introduces a small fix in the views documentation. The example code was mixing `async/await` and `then` method chaining. 
The MR changes the example to use only the `async/await` approach for readability improvement.
> Small fix in the JS example in views doc

- IHP/FetchRelated.hs
This PR adds a function called `collectionFetchRelatedOrNothing` and addresses issue #982.
> Implement collectionFetchRelatedOrNothing

- Guide/authentication.markdown
This didn't compile for me without the parameter `user`. Also, `#isConfirmed` with a capital C didn't compile for me.
> Update authentication guide

- IHP/Job/Queue.hs
- IHP/Job/Runner.hs
- IHP/Job/Types.hs
- ihp.cabal
- ihp.nix
- shell.nix
The job queue table's now have a `run_at` column. Jobs are only executed after the specified time.
This requires a migration for all userland job queues, to add the missing run_at column. The default value for existing jobs can be the created_at column.
The job runner is now also polling the job queue at regular intervals as otherwise scheduled jobs will not be picked up when there's no activity on the job queue table.
> Allow scheduling jobs at a specific time with runAt

- Guide/file-storage.markdown
- IHP/ControllerSupport.hs
- IHP/FrameworkConfig.hs
Previously it was not possible to increase e.g. the limit of 10 files per request in IHP. The limits are applied by the Network.Wai.Parse middleware.
It's now possible to override the default ParseRequestBodyOptions in the application's Config.hs
> Allow configuring file upload limits from userland

- IHP/QueryBuilder.hs
'Fix' for git@github.com:digitallyinduced/ihp.git #1034: join queries need to be regarded as complex queries.
> refuse to build union query if one of the queries contains joins

- IHP/Pagination/ControllerFunctions.hs
- IHP/QueryBuilder.hs
- Test/QueryBuilderSpec.hs
Fix for #1035: so far, only the filter functions for joined tables prefixed the column names with the table names. In the present case, this resulted in the column name "id" becoming ambiguous, being a columns in both joined tables.
All the filter functions now prefix the column name with the table name to rule out such ambiguities.
> Table prefix column names

- Guide/form.markdown
All `allEnumValues` very useful function but I've forgotten about it a couple times and thought it would be useful to have an extra reference to it right next to the existing Form documentation on `CanSelect` and selectfields. At the moment it is only referred to in `recipes.markdown`.
> Added allEnumValues helper docs to Form documentation

- lib/IHP/static/helpers.js
This PR would make the behaviour for a failed Form request the same with and without Turbolinks. The pattern is that if a   `Left branch` failed form submission leads to a `render SomeView {..}` the form creation action and controller URL will match. In this case we likely do not want the url to update to the target for the form creation because on a user manual browser refresh this will trigger a `GET` request to the Create action which leads to a `400` error (those endpoints require `POST` by IHP convention). This PR catches the url equality and doesn't update the local url so a refresh triggers the page reload.
Tested [here](https://github.com/Montmorency/ihp-create-action).
> potential mod for create form actions to helpers.js 

- IHP/ValidationSupport/ValidateField.hs
```
-- | Validates that value is a valid slug
--
-- >>> isSlug "i-am-a-slug"
-- Success
--
-- >>> isSlug "I-AM-A-Slug (Copy)"
-- Failure "is not a valid slug (consisting of only letters, numbers, underscores or hyphens)"
```
> Slug validator

- Guide/form.markdown
Accidentally pluralized data type. Could be confusing for someone following docs.
> Typo on ContentType in CanSelect form docs.

- IHP/IDE/CodeGen/ApplicationGenerator.hs
- ihp.nix
Suggestion that if `app.js` is shipped with ihp-boilerplate might make sense to have it in the CodeGen as well. E.g. a developer who opens a test project and starts playing with customizing `app.js`  but changes aren't getting picked up in starter project. Also attaching new cache buster to this automatically makes sure production app.js changes are picked up straight away.
> Codegen app.js

- IHP/HaskellSupport.hs
- Test/HaskellSupportSpec.hs
This adds a function `setIfJust` which is similar to `set` but which takes a `Mabye value` and updates the record if the value is `Just`, and doesn't change it if it's `Nothing`.
> add setIfJust which ignores updates on Nothing

- Guide/oauth.markdown
I'm not sure, but I think the actual intention was for this path to be GoogleConnectCallbackAction
> Update OAuth documentation

- IHP/ServerSideComponent/HtmlDiff.hs
- IHP/ServerSideComponent/HtmlParser.hs
- Test/SchemaCompilerSpec.hs
- Test/ServerSideComponent/HtmlDiffSpec.hs
Fixes #1192.
Before this is merged, I'd love to know if there is also a testsuite for the client-side HTML patching code.
> Fix "Non-exhaustive patterns in function nodeOuterHtml"

- IHP/Job/Dashboard.hs
- IHP/Job/Dashboard/View.hs
In a last [commit](https://github.com/digitallyinduced/ihp/commit/272565698c56dcfeb56b474e3d8e493c6a4b5394) the "retry" button on the job list view has been fixed, but not on the Job's detail page. There was also a wrong success message (talking about "job record deleted") which this PR also addresses.
> Fix job dashboard retry

- lib/IHP/static/vendor/ihp-ssc.js
IHP's HTML parser outputs HTML-escaped strings but ihp-ssc.js does not unescape them when inserting them into DOM. This means SSC is mostly broken for any text containing chars like `"`, especially for `<input>`s.
> SSC: use unescaping

- ProjectGenerator/bin/ihp-new
Currently, `ihp-new` runs `cachix use digitallyinduced` more-or-less unconditionally.
Since that's similar in some ways to adding a 3rd party repository under a traditional apt/dnf model\*, better to ask (and notify) the user first, especially since it isn't *strictly* necessary. \**Eventually, reproducible builds should make it much safer than adding a 3rd party repo, but we're not there yet, as far as I understand.*
I'm happy to tweak the wording, which is based on the description at https://ihp.digitallyinduced.com/Guide/package-management.html#binary-cache and trying to mimic the style of the other places in the script.
> Ask before using DigitallyInduced cachix cache

- IHP/Job/Dashboard.hs
- IHP/Job/Dashboard/Utils.hs
- IHP/Job/Dashboard/View.hs
Addresses #1198
I tested locally by creating 65 job instances in a sample project and checking that the pagination renders as expected for various page and window sizes:
* No pagination is rendered when all items fit on a single page.
* Only the necessary number of pages are listed when `window size > total pages`.
* Only the specified number of items are rendered per page when selecting the "items per page" dropdown.
* Clicking on an arbitrary page number navigates to that page.
* Clicking on the "previous" and "next" arrows navigates to the associated pages.
There's still redundancy with `IHP.Pagination.ControllerFunctions.paginateWithOptions`.
I tried to use that function but couldn't figure out how to initialize a `QueryBuilder` with a `Text`-valued table name. This isn't possible, …
> Use standard `renderPagination` in list page for Jobs Dashboard

- Guide/tailwindcss.markdown
When creating a new IHP project and installing Tailwind, Tailwind 3 will be installed.
There is a slight difference in the configuration file, where the `contents` and `options` are now moved up in the hierarchy and the tailwind cli throws an error if using the old structure.
Other than that, there aren't any incompatability issues with Tailwind 3 as I am following this guide with this modification in two fresh projects now :+1: 
CC @amitaibu
> Tailwind 3 support

- IHP/ErrorController.hs
> Add `overflow-x` to code in an error message

- Guide/database.markdown
- IHP/ModelSupport.hs
I've also renamed `model` to `record`, to keep consistency. However, I'm getting this error now:
> Add `deleteRecordByIds`

- Guide/config.markdown
- IHP/FrameworkConfig.hs
- IHP/Server.hs
The PR adds a `CustomMiddleware` option to `FrameworkConfig`.  By providing a middleware here the user can run any arbitrary WAI middleware, providing a real "escape-hatch" for IHP.  It would even be possible, for example, to combine a Servant app or Yesod app with an IHP app using this option. Further examples are provided in the docs.
> Add CustomMiddleware option for user-provided WAI middleware

- IHP/DataSync/Controller.hs
- IHP/DataSync/Types.hs
- lib/IHP/DataSync/ihp-datasync.js
- lib/IHP/DataSync/ihp-querybuilder.js
- lib/IHP/DataSync/index.js
- lib/IHP/DataSync/transaction.js
This adds a new high-level `withTransaction` function and a lower-level `Transaction` object to deal with postgres transactions from DataSync.
The following operations can be used from within a transaction:
- createRecord, createRecords
- updateRecord, updateRecords
- deleteRecord, deleteRecords
- query
Example Usage:
```javascript
const addTask = async () => {
console.log('length before transaction', (await query('tasks').fetch()).length); // => 0
await withTransaction(async transaction => {
await transaction.createRecord('tasks', { title: 'hello world', userId: getCurrentUserId() })
console.log('length outside of transaction', (await query('tasks').fetch()).length); // => 0
console.log('length in transaction', (await transaction.query('tasks').fetch()).length); // => 1
}) …
```
> Added transactions to DataSync

- IHP/WebSocket.hs
The 'withPingThread'  function of the websockets package is not dealing with missing pong messages at all. This means that websocket connection might never be cleaned up when the connection is not closed correctly.
This change implements a manual ping and pong handling that closes a connection after not receiving a pong message within 10 seconds after sending a ping to the client.
> Implemented expected timeout handling in websockets

- IHP/ModelSupport.hs
- IHP/Pagination/ControllerFunctions.hs
- IHP/QueryBuilder.hs
- IHP/SchemaCompiler.hs
- Test/SchemaCompilerSpec.hs
This allows for easier building custom data records that use an existing table
> Make query builder use Table API to access the table name

- Guide/package-management.markdown
- NixSupport/default.nix
A small change to `IHP/NixSupport/default.nix` allows for developer to customize the extensions available to postgres. E.g. in their `app/default.nix` they can add the line:
```
import "{$ihp}/NixSupport/default.nix" {
ihp = ihp;
postgresExtensions = (p: [ p.postgis ]);
```
to enable postgis for geographic db tools in posgresql.
> Postgres Extensions in Dev Environment.

- IHP/DataSync/DynamicQuery.hs
- IHP/DataSync/DynamicQueryCompiler.hs
- Test/DataSync/DynamicQueryCompiler.hs
E.g. a condition like `where('field', null')` needs to add a SQL condition like `WHERE field IS NULL` instead of `WHERE field = NULL`
> Fixed DataSync not generating the correct sql query for null conditions

- IHP/DataSync/Controller.hs
- IHP/DataSync/DynamicQuery.hs
- IHP/DataSync/DynamicQueryCompiler.hs
- IHP/DataSync/REST/Controller.hs
- Test/DataSync/DynamicQueryCompiler.hs
- lib/IHP/DataSync/ihp-querybuilder.js
This allows a simple search fulltext search to implemented like this:
```javascript
function ProductSearch() {
const [searchQuery, setSearchQuery] = useState('');
const onChange = useCallback(event => setSearchQuery(event.target.value), [ setSearchQuery ]);
const products = useQuery(query('products').whereTextSearchStartsWith('ts', searchQuery));
return <form>
<input type="text" className="form-control" value={searchQuery} onChange={onChange}/>
<div>
Result: {products?.map(product => <div>{product.name}</div>)}
</div>
</form>
}
```
> Added tsvector based fulltext search for DataSync

- IHP/HSX/Parser.hs
Allow `nonce` attribute so it's possible to set a really strong Content Security Policy for script and link tags:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src 
Also allow `referrerpolicy` as this a security attribute used by some cdns that probably is nice to have even though it still works if removed.
Example: `<script src="https://cdnjs.cloudflare.com/ajax/libs/timeago.js/4.0.2/timeago.min.js" integrity="sha512-SVDh1zH5N9ChofSlNAK43lcNS7lWze6DTVx1JCXH1Tmno+0/1jMpdbR8YDgDUfcUrPp1xyE53G42GFrcM0CMVg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>`
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy
> Allow nonce and referrerpolicy

- Guide/database.markdown
Changed `Postgress` to `Postgres`.
> Fix spelling of Postgres

- Guide/installation.markdown
`nix.trustedUsers` is either invalid or deprecated by `nix.settings.trusted-users`
> Update NixOS configuration

- ihp-hsx/IHP/HSX/Parser.hs
To make slots for custom elements work, a `slot` parameter needs to be enabled.
Usage example:
```html
<my-paragraph>
<span slot="my-text">Let's have some different text!</span>
</my-paragraph>
```
Source:
https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_templates_and_slots#adding_flexibility_with_slots
> Add slot parameter for custom elements

- IHP/ControllerSupport.hs
- IHP/RouterSupport.hs
- IHP/ServerSideComponent/RouterFunctions.hs
This PR introduces an optional `router` function for `FrontController`s, which allows handling the routing for that FrontController only in that function, or extending the `defaultRouter`, which is the previous behavior. Additionally, the function allows using `putContextRouter`, a new function that is used to modify the `ControllerContext` during routing, ~*before*~ ~*after*~ *before* `initContext` is called.
The default implementation for `router` is `router = defaultRouter`, which is 100% backwards-compatible.
An example of why this is useful and how it is used is this router implementation:
```haskell
instance FrontController WebApplication where
... -- the previous code assigning controllers is still required
router additionalControllers = do
mlocale <- optional do
string "/"
string …
```
> Single Routing Entrypoint

- .ghci
- IHP/Fetch.hs
- ihp-hsx/IHP/HSX/Parser.hs
- ihp-hsx/ihp-hsx.cabal
- ihp.cabal
- lib/IHP/Makefile.dist
- lib/IHP/applicationGhciConfig
This branch allows us to use GHC's new record dot syntax in IHP projects:
```haskell
-- old:
get #id project
--new:
project.id
```
This syntax doesn't work in HSX yet sadly.
> Enable record dot syntax

- ihp-hsx/ihp-hsx.cabal
> Updated bounds for ihp-hsx package

- IHP/FileStorage/Config.hs
- IHP/FrameworkConfig.hs
- IHP/Prelude.hs
Fixes https://github.com/digitallyinduced/ihp/issues/1503
Instead of:
```
RunProdServer: MErrVMissingCredentials
```
We now get:
```
*** Exception: MErrVMissingCredentials
CallStack (from HasCallStack):
ConfigException, called at IHP/IHP/FrameworkConfig.hs:570:38 in main:IHP.FrameworkConfig
configIO, called at IHP/IHP/FileStorage/Config.hs:75:12 in main:IHP.FileStorage.Config
initMinioStorage, called at Config/Config.hs:18:5 in main:Config
```
> Added callstacks to exceptions thrown during config

- exe/IHP/IDE/DevServer.hs
- lib/IHP/applicationGhciConfig
Fixes #1506
This mirror the expected behaviour when running e.g. `import Web.Types` (this fails without a `:l Main` first)
> Run `:l Main` automatically when opening ghci

- Guide/scripts.markdown
- Test/HSX/QQSpec.hs
- ihp-hsx/IHP/HSX/HsExpToTH.hs
Mapped a few more data types from HsSyn to TH. Pattern matching on Constructors and infix operators like (:), (,) should now work in [hsx||] blocks. This should address issue #1495. Note the Constructors in hsx blocks don't support Type Annotations (may require ghc 9.4.2?).
> Hsx conpat

- IHP/FrameworkConfig.hs
Using `envOrDefault` with `FilePath` e.g.:
```
logFilePath <- envOrDefault "Log/app.log"  "LOG_PATH"
logger <- liftIO $ newLogger def {
level = Info,
formatter = withTimeAndLevelFormatter,
destination = File logFilePath (SizeRotate (Bytes (4 * 1024 * 1024)) 7) defaultBufSize
}
option logger
```
required an instance of `EnvVarReader String` for `envOrDefault`.
> Adding String instance to EnvVarReader

- .github/workflows/build.yml
as advised in https://ihpframework.slack.com/archives/C01DX8592H0/p1669795611222709?thread_ts=1669749271.272259&cid=C01DX8592H0
> Cache more Haskell packages

- ProjectGenerator/bin/ihp-new
this was misconfiguring direnv for zsh shells previously
>  fix zsh config in ihp-new

- Guide/editors.markdown
Now that haskell-language-server is included with IHP, and LSP support is built-in to the newest release of Emacs, it makes sense to change the default recommendation to using those.
(I'm not very happy with the workaround to make emacsclient work as an IHP_EDITOR, though it's a fairly common trick since it expects args in a different syntax than `code --goto`.)
> doc Emacs eglot setup

- Test/HSX/ParserSpec.hs
- ihp-hsx/IHP/HSX/Parser.hs
> hsx: Allow `{ ...values}` spread, with a space in front

- Guide/installation.markdown
The devcontainer config used for [Codespaces](https://github.com/rvarun11/codespaces-ihp) can be used for local devcontainers with a minor modification.
> Add info for VSCode Devcontainers

- IHP/ModelSupport.hs
Related question in the IHP Slack:
> There's a function I find myself writing in specific over and over again, and I'd love to be able to write a general form. E.g.
getUserPosts user posts =
filter (\p -> p.userId == user.id) posts
Given an A, and a list of Bs with an (Id A) field, find all Bs that refer to A.
Does anyone know how to write that? I don't know how to write the
p.userId
expression as a generic
p.(id A)
> Added onlyWhere, onlyWhereReferences and onlyWhereReferencesMaybe

- IHP/Modal/ViewFunctions.hs
I replaced the close button previously used for modals using the times-symbol, which looks bad in Bootstrap 5. It now uses the new btn-close class (instead of the old close class).
See:
- https://getbootstrap.com/docs/5.2/migration/#close-button
- https://getbootstrap.com/docs/5.2/components/modal/#modal-components
Note that I tested the HTML code changes in the developer console of my browser, but haven't tested this change in an actual IHP project yet.
> Fix modal close button

- IHP/PGListener.hs
/claim #1621
Hi! 
I figured it would be fun to give this bounty hunt a try :)
I believe this should solve #1621 although I'm unsure of the best way to test a failed connection. Tested AutoRefresh with it and it seemed to work fine!
Added a sleep before re-running the function and replacing forever with a recursion.
Double the sleep delay for the next retry until it reaches a minute, then it retries every minute from then on.
I don't know what should be the best amounts here so feel free to suggest other values than min 500ms and max 1 minute.
> Add backoff strategy when a PGListener fails

- Guide/tailwindcss.markdown
A key reason of the value of including this, apart from many's distaste for npm, is that it makes deployment much simpler when npm is not a requirement
> Add mention of standalone CLI and ihp-tailwind-bootstrapper as alternative to npm

- Guide/file-storage.markdown
On edit, we expect to see the existing uploaded file/ image. PR explains how to do it.
> Give example on how to see an existing image on file upload

- CONTRIBUTING.md
Make it easier not to accidentally commit changes to `ihp.nix`
> Document command to ignore changes to `IHP/ihp.nix`

- IHP/ErrorController.hs
- IHP/IDE/ToolServer.hs
- IHP/Server.hs
- Test/RouterSupportSpec.hs
- Test/SEO/Sitemap.hs
- devenv.nix
- ihp.cabal
- ihp.nix
The wai-app-static package is more actively maintained. The old wai-middleware-static had some issues, particular related to leaking file handles. Also wai-app-static has better cache handling for our dev mode
> Use wai-app-static instead of wai-middleware-static

- Guide/file-storage.markdown
- Show how to use `additionalAttributes` to avoid hand coding the `<input>` field
- Explain how to have server-side validation for required file uploads, so one could see something like this
> File upload doc improvements

- lib/IHP/static/helpers.js
So you can have e.g.
<button class="btn btn-primary" type="submit" formaction={CreateAction}>
Submit
</button>
<button class="btn btn-secondary" type="submit" formaction={SaveProgressAction} formnovalidate>
Save progress
</button>
> helpers.js: Support formAction attribute on <button>

- lib/IHP/DataSync/ihp-datasync.js
In browser event on the dom but in mobile/react native the event is out of scope.
> Removed out of scope event from reconnect.

- Guide/jobs.markdown
Without registering the workers the jobs don't run.
> Update the Jobs doc in the Guide

- Guide/file-storage.markdown
- IHP/FileStorage/ControllerFunctions.hs
- Explanation on how to use the `UploadedFile` (or any other name)  record
- Add a `refreshTemporaryDownloadUrl` helper function
For posterity, working PR using the helper function here https://github.com/amitaibu/ihp-landing-page/pull/18
> `UploadedFile` record helper and guide

- Guide/hsx.markdown
- IHP/ServerSideComponent/HtmlDiff.hs
- IHP/ServerSideComponent/HtmlParser.hs
- Test/HSX/QQSpec.hs
- Test/ServerSideComponent/HtmlDiffSpec.hs
- ihp-hsx/IHP/HSX/Parser.hs
- ihp-hsx/IHP/HSX/QQ.hs
| hsx | Html |
| -- | -- |
| ![image](https://github.com/digitallyinduced/ihp/assets/125707/dd4d7ed3-f0df-464e-9381-5c79996e055a) | ![image](https://github.com/digitallyinduced/ihp/assets/125707/157f9c57-6d69-4c53-8a28-dfb3e5cf7e69) |
fixes #1722
> Add `NoRenderCommentNode` to hsx

- IHP/IDE/FileWatcher.hs
The file watcher used by the dev server to automatically reload on changes seems to have issues with large directories with Ubuntu (see https://github.com/digitallyinduced/ihp/issues/1714).
The System.FSNotify API does not allow us to exclude sub-trees from the paths watched by `watchTree`. Instead we can watch file changes in the root directory using `watchDir` and use `watchTree` on sub-directories excluding `.direnv` and `.devenv` which are known to be large directories and are not relevant with regard do reloading.
We also keep track of directories added and removed from the root directory and watch them accordingly.
> feat: do not watch .direnv and .devenv subdirectories

- IHP/IDE/FileWatcher.hs
The call to putMVar waits until the file watcher state MVar is empty. As it's never emptied, the file watcher hangs after watching the first sub directory (typically 'Config'). This is fixed by using modifyMVar_, which doesn't hang when the MVar is full
Fixes https://github.com/digitallyinduced/ihp/issues/1714
> Fixed putMVar blocking file watcher

- CONTRIBUTING.md
Fixes https://github.com/digitallyinduced/ihp/issues/1740
@kodeFant @Eisfunke can you take a look at this? This documentation is about the new branching structure for nix flake releases of IHP
> Added documentation about the new version branches

- UPGRADE.md
The db is not dropped anymore when updating to the latest IHP
> Removed outdated upgrade instructions

- IHP/LibDir.hs
- NixSupport/default.nix
- UPGRADE.md
- exe/IHP/IDE/DevServer.hs
- flake-module.nix
- lib/IHP/Makefile.dist
This PR removes all of `build/ihp-lib` and replaces with an env var managed by devenv.
Fixes https://github.com/digitallyinduced/ihp/issues/1751
> Improved ihp lib

- Guide/editors.markdown
- Guide/installation.markdown
Some doc stuff for the new flake architecture.
While nix-env-selector *should* work through the flake-compat default.nix, we should rather recommend the direnv extension for VSCode so it uses the correct environment. That extension also tends to work more reliably and can be used in non-nix projects as well, so it's the better choice IMO.
> Add docs for enabling flakes, recommend direnv extension

- flake-module.nix
Ref: https://github.com/digitallyinduced/ihp/issues/1763
This makes it quick to get the right `IHPSchema.sql` for server provisioning by
```
nix build .#ihp-schema
```
> Flake ihp schema package

- flake-module.nix
Potential fix for https://github.com/digitallyinduced/ihp/issues/1760
```bash
nix build .#migrate
./result/bin/migrate
```
Likely (but untested) this can be used in nixos as:
```nix
environment.systemPackages = with pkgs; [ ihpApp.migrate ];
```
Then a global `migrate` command would be available
> Added a migrate output to the IHP flake

- Guide/oauth.markdown
I tried adding `ihp-oauth-google` to `flake.nix`, but I'm getting this error
> Update oauth with the new `flake.nix`

- flake-module.nix
(gnu)make is (still) needed for various stuff in the devenv, including the haskell IDE stuff.
I noticed that we don't yet have make added to the IHP devenv because don't have a global make install on my NixOS system as I rely on direnv and flakes to make it available where I need it. That led to unexpected and hard to debug errors in my VSCode haskell IDE stuff, because the hie-bios stuff is generated through a make task, which didn't work without make.
By adding make to the devenv, users don't need a global make install and we make sure it's available.
> Add make to devenv

- Guide/mail.markdown
- Guide/testing.markdown
With Mailhog we can catch emails, and use the API to get the contents of the emails in tests.
> Guide on how to test emails with Mailhog API

- Guide/controller.markdown
- Guide/validation.markdown
- IHP/IDE/CodeGen/ControllerGenerator.hs
- Test/IDE/CodeGeneration/ControllerGenerator.hs
PR also changes the generator to always use `@'[` for `fill` instead of the `@[` -- as it seems it works regardless of the number of elements in the list.
> Add guide on conditional `fill` and security concerns

- flake-module.nix
Usage from an IHP app:
```
nix build .#unoptimized-docker-image
nix build .#optimized-docker-image
```
> Add out of the box docker image build targets

- Guide/package-management.markdown
Instead of installing cabal2nix permanently for one-time use with `nix-env`, rather use `nix-shell` which is also the recommended way on [NixOS packages](https://search.nixos.org/packages?channel=23.05&show=haskellPackages.cabal2nix&from=0&size=50&sort=relevance&type=packages&query=cabal2nix).
> Recommend running a nix ad-hoc shell instead of nix-env

- Guide/editors.markdown
- flake-module.nix
- Adds `withHoogle` support back: it was missing since the migration to flakes/flake-parts.
- Updates documentation to reflect the changes in configuration and usage since the migration to flake-parts.
> Add back withHoogle support

- Guide/layout.html
- IHP/RouterSupport.hs
- README.md
> Update old forum links to new discuss forum

- IHP/SchemaCompiler.hs
Example code of how I'm using it, for adding steps counter.
```haskell
breadcrumb =renderBreadcrumb
[ breadcrumbLink "Overview" (ShowLearningMapNameAction learningMapName.id)
, breadcrumbText $ (renderLearningMapStep learningMapStep) ++ cs (" (Step " ++ (show $ position learningMapStep) ++ " of " ++ (show totalElements) ++ ")")
]
position :: LearningMapStep -> Int
position step = fromEnum step + 1
-- Calculate total number of elements
totalElements :: Int
totalElements = fromEnum (maxBound :: LearningMapStep) + 1
```
This results with:
> Add `Bounded` to Enums

- Test/SchemaCompilerSpec.hs
Oops, `Bounded` PR was merged before I got to fix the tests 🙈
> Fix Enum tests

- Guide/file-storage.markdown
I've updated `nix flake update`on https://github.com/amitaibu/ihp-landing-page/ , and had to fix the error:
```
Ambiguous module name ‘Crypto.PubKey.RSA’:
it was found in multiple packages: crypton-0.32 cryptonite-0.30
```
> Fix imports for signed token example

- IHP/Test/Database.hs
The old importSql function in createTestDatabase for Mocking used a raw byte string and then imported Schema as a PGConnect/PGQuery. This ran into parsing issues when init a complex schema into test database. The IDE had no problem importing same Schema with psql. This PR updates testDatabase to work with psql import.
> Bringing Test Suite sqlImport in line with IDE. 

- ihp-openai/IHP/OpenAI.hs
`streamCompletion` previously failed often (not always though), because `parseResponseChunk` assumed that a chunk of the input stream from the OpenAI api would only ever contain a single message. However, the API often sends two data messages in one chunk separated by two newlines (which the format allows) together at the start of a completion, which failed to parse as JSON. Because the unparsed chunks were stuck in the buffer, they were always appended to the beginning for all other chunks, which therefore also didn't parse, leading to all messages not being parsed.
I fixed this by re-chunking the stream into lines with `Streams.lines`. And also added parsing logic for comments, multi-line messages and messages separated by double-newlines, as specified in the Server-Sent Events spec the …
> fix(openai): parsing of streaming completions

- IHP/SchemaCompiler.hs
- Test/SchemaCompilerSpec.hs
I'd like to have an associate list with an enum as key.
Assuming Foo is an Enum:
```haskell
import qualified Data.Map as Map
let value = Map.lookup Foo treeJson
```
Without this PR we get error:
```
Could not deduce (Ord ProductItemType)
arising from a use of ‘Map.lookup’
```
> Add `Ord` to Enums

- Guide/database.markdown
Make the "Common pitfalls" part of the main explanation
> Improve `withTransaction` docs

- Guide/examples.markdown
Attics no longer uses IHP but rather Ruby on Rails.
> Remove Attics in examples.markdown

- ihp-hsx/IHP/HSX/Parser.hs
HTMX has extracted the SSE functionality to a plugin and renamed the attribute "hx-sse" to two new attributes ("sse-connect" and "sse-swap").
For details and reasoning for this change see:
https://htmx.org/extensions/server-sent-events/#migrating-from-previous-versions
> Allow attributes sse-connect and sse-swap

- IHP/View/CSSFramework.hs
- IHP/View/Form.hs
- IHP/View/Types.hs
- Test/View/CSSFrameworkSpec.hs
- Test/View/FormSpec.hs
Sometimes we may wish to have the submit button disabled. In my case, I later enable it via JS, if the form has changed.
```haskell
renderForm :: LandingPage -> Html
renderForm landingPage = formFor landingPage [hsx|
{(textField #title)}
{submitButton {label = "Save Landing page", buttonDisabled = True}}
|]
```
> Allow a submit button to be disabled

- IHP/Controller/FileUpload.hs
- IHP/FileStorage/ControllerFunctions.hs
Right now we return a `Just file`, even when there's no file.
This is similar to the check we already have here https://github.com/digitallyinduced/ihp/blob/d0658832f6d51160678f3a03d0920f3621b844e2/IHP/FileStorage/ControllerFunctions.hs#L333
> `fileOrNothing` should check `fileContent` isn't empty

- IHP/IDE/FileWatcher.hs
- ihp.cabal
> Add debounce to fsnotify

- Guide/form.markdown
- IHP/View/CSSFramework.hs
- IHP/View/Form.hs
- IHP/View/Types.hs
> Add `urlField`

- lib/IHP/Makefile.dist
Removes `hie.yaml` initialization as it's already present in the [ihp-boilerplate](https://github.com/digitallyinduced/ihp-boilerplate/blob/master/hie.yaml)
> Remove HLS config initialization

- Guide/mail.markdown
https://discuss.ihp.digitallyinduced.com/t/use-urlto-in-a-mail/29
> Show example how to send a link from Mail

- ProjectGenerator/bin/ihp-new
Fixes https://github.com/digitallyinduced/ihp/issues/1787
> ihp-new: Create git repo to avoid issues when IHP is part of a larger git repo

- Guide/testing.markdown
I guess the naming got updated, but not in the docs. In my tests the attribute is called `haskellPackages`, not `haskellDeps`.
> Fix naming in test docs

- Guide/search/package-lock.json
- Guide/tailwindcss.markdown
I updated the tailwindcss instructions to use `devenv` to launch tailwind.
I removed the redundant `make tailwind-dev` instructions to keep things simple. But let me know if you prefer to keep them for users of older IHP versions.
> Update tailwindcss instructions

- Guide/mail.markdown
- IHP/EnvVar.hs
> Allow easier SMTP config envs

- IHP/SchemaCompiler.hs
- Test/SchemaCompilerSpec.hs
I think this fixes the issue I described in #1914.
I would love to add unit tests for this, however I wasn't able to find the right place to put them - If unit tests are wanted here I'd love a little guidance.
> fix SchemaCompiler filterPrimaryKey

- .envrc
- IHP/ControllerSupport.hs
- IHP/ErrorController.hs
- IHP/IDE/ToolServer.hs
- IHP/RouterSupport.hs
- IHP/Server.hs
- Main.hs
- Test/Controller/AccessDeniedSpec.hs
- Test/Controller/NotFoundSpec.hs
- Test/RouterSupportSpec.hs
- Test/SEO/Sitemap.hs
- Test/ViewSupportSpec.hs
This PR makes the request logger only log requests that are to actual IHP controllers, ignroing any static files. This was the behaviour until a while ago.
> Request logger static files

- Guide/editors.markdown
- Guide/search/package-lock.json
Added a useful emacs config with direnv and lsp/lsp-ui. Addresses issue #1846.
> Emacs direnv

- lib/IHP/Makefile.dist
`make db` right now silently moves on if there's an error in the Schema or in the Fixture. It should not be like that.
> Make it easier to spot schema + fixture errors

- IHP/ErrorController.hs
This was the expected behaviour, but turns out I missed one place
> Only track exception (e.g. with sentry) in production

- IHP/ApplicationContext.hs
- IHP/Controller/RequestContext.hs
- IHP/Controller/Response.hs
- IHP/Controller/Session.hs
- IHP/ControllerSupport.hs
- IHP/EnvVar.hs
- IHP/IDE/FileWatcher.hs
- IHP/IDE/ToolServer.hs
- IHP/RouterSupport.hs
- IHP/Server.hs
- IHP/Test/Mocking.hs
- Test/Controller/AccessDeniedSpec.hs
- Test/Controller/CookieSpec.hs
- Test/Controller/NotFoundSpec.hs
- Test/Controller/ParamSpec.hs
- Test/View/CSSFrameworkSpec.hs
- Test/View/FormSpec.hs
- Test/ViewSupportSpec.hs
Moved the session vault key from the ApplicationContext and RequestContext data structure to a global variable. This is the suggested way by the WAI developers.
See https://www.yesodweb.com/blog/2015/10/using-wais-vault
> Simplify session vault key handling

- Guide/spoilify.js
Fixes #1897 
The substantive change is on line 49, everything else is either:
1. Comments describing what the code is doing.
2. Changing a few `var` to `const` where appropriate.
This patch just increases the scope of when the section-discovery code stops adding elements to a section. Before, it would keep going until it hit an `<h2>` element, and the section on Nix Flakes is after a `<h3>`, so it would keep munching up elements until it hit _Installing IHP_.
> Fix blank 'Enabling Flakes' section.

- Guide/installation.markdown
- Provide clarity on whether to install Flakes (recommend users enable the feature).
- Add link to beginners' guide to NixOS & Flakes.
- Rewrite awkward wording and grammar, like '[...] all the Nix stuff is being handled for you.'
- Provide the user with context on Flakes and why they need to be enabled, without overwhelming them.
> Rewrite 'Enabling Flakes' section of Installation docs.

- exe/IHP/CLI/NewSessionSecret.hs
This is the output I get when I execute on Ubuntu:
```
$ new-session-secret
vKfe21qHkQwwLAf+vWVEhywVMujoZlsg2ZBRuIKlrAfM4TlGgaaj5MOfplDdmpOlkqTkAttpy32GnLhPIwiF7+kB+e4ofoyOkqWNz9//pZts7jxkdgOc8MoY7FY3FH8F%   
```
Notice the `%` on the end.  PR is an attempt to add a new line at the end of the string. 
However, I don't know how to execute this locally to test it.
> Remove `%` from sessionSecret

- flake.nix
devenv up failing on macs in latest version. This new devenv version should fix it.
> Pinning devenv with Mac Fix for Process Sockets

- IHP/Log/Types.hs
- Test/SchemaCompilerSpec.hs
- ihp-ide/IHP/SchemaCompiler.hs
I've split up the generated haskell modules into even more files for faster builds on large projects. And added some strictness annotations to the logger
> Some small improvements

- IHP/ModelSupport.hs
- Test/SchemaCompilerSpec.hs
- ihp-ide/IHP/SchemaCompiler.hs
We already have updateRecordDiscardResult, this one is still missing. Useful if you want to e.g. schedule an IHP job but don't care about the result
> Added createRecordDiscardResult

- Guide/htmx-and-hyperscript.markdown
slightly more fool-proof documentation
> htmx guide: Note the usual things to remember when adding controller

- Troubleshoot/ihp-troubleshoot
As it's no longer required, since we're using `devenv up`
> ihp-troubleshoot should look for `flake.nix` instead of `start` script

- Guide/file-storage.markdown
With current fix, the image style is created with the correct name, as the original file.
> Fix docs about ImageStyle

- Guide/deployment.markdown
This is documenting the code in https://github.com/digitallyinduced/ihp-boilerplate/pull/35
> Document how to use the AWS terraform config

- NixSupport/default.nix
- devenv-module.nix
- flake-module.nix
- flake.lock
When hosting multiple ihp apps on a particular server it is helpful for debugging/maintenance/tooling to be able to inspect which binaries are in the production servers /nix/store by their name (not just hash). This is consistent with all other nixpkgs that contain the hash and the package name in the store. 
For managed production clusters it is also  nice for roll back to be able to give semver names to app packages so that it is easy to instantly roll back to a prev version of app binary on a prod server if required. This PR adds option of appName to ihp flake-modules so users can specify the appName. The appName option gets passed all the way to ihp's (un)optimized-prod-server package `mkDerivation` (where it is called `name` and is a standard attribute for nix's mkDerivation.). We …
> Add appName To options for flake.

- ProjectGenerator/bin/ihp-new
I'm on Linux Mint (an Ubuntu derivative). I'm using the bash shell. The file `~/.bash_profile` doesn't exist on my machine. My `~/.bashrc` file contains the `eval "$(direnv hook bash)"` line. 
The script displayed a `grep` error saying that the `~/.bash_profile` file does not exist and instructed me to add the line above to `~/.bashrc`, which I already did.
It looks like the fix works in my config. I didn't try it on `zsh`. Unfortunately I'm not sure if this is a POSIX-compliant solution.
> Fix grepping for direnv, add profile files to messages

- Guide/database-migrations.markdown
- IHP/SchemaMigration.hs
- NixSupport/nixosModules/options.nix
- NixSupport/nixosModules/services/migrate.nix
- ihp-ide/IHP/IDE/SchemaDesigner/Controller/Migrations.hs
- ihp.nix
Adds an environment variable so user can run migration systemd service from any directory on FileSystem. Useful in certain production situations. Defaults to the previous value. Docs updated.
> Migration path Env Var.

- Guide/jobs.markdown
Add documentation for scheduling future job execution using the runAt field. Reorganize job execution docs to clearly distinguish between immediate and scheduled runs. Note polling interval for scheduled jobs.
> docs: add scheduled job execution with runAt field

- ihp-ide/IHP/IDE/SchemaDesigner/View/Layout.hs
This PR adds the ON DELETE constraint information to the Schema Designer, making it easier to see constraint types without opening the Edit Foreign Key modal or checking the schema directly.
> Show On Delete constraint in the schema designer

- IHP/Pagination/ControllerFunctions.hs
Changes examples to use [] to match the expected [Action] parameter type.
> Refactor pagination SQL queries to use generic paramaters

- IHP/Server.hs
- NixSupport/haskell-packages/warp-systemd.nix
- NixSupport/mkGhcCompiler.nix
- NixSupport/nixosModules/services/app.nix
- devenv-module.nix
- ihp.cabal
- ihp.nix
Found this package when looking at https://blog.cachix.org/posts/2020-12-23-post-mortem-recent-downtime/
> integrate warp-systemd for more reliability in production deployments

- IHP/ErrorController.hs
debugging is easier if the exception is printed to the error log in production
> print exceptions to log

- Guide/realtime-spas.markdown
This updates some outdated documentation. [Loading the JS SDK](https://ihp.digitallyinduced.com/Guide/realtime-spas.html#loading-the-js-sdk) is still outdated since `ihp-datasync.js` was moved outside of `vendor/`, see https://github.com/digitallyinduced/ihp/commit/af883a407020b03945464bbbcb507be58866e1c3. This raises the question: how should `ihp-datasync.js` and `ihp-querybuilder.js` be loaded in the frontend?
> Update realtime SPA docs

- flake.lock
- flake.nix
This is an attempt to fix the error when trying to push a binary to cachix
https://github.com/digitallyinduced/ihp/actions/runs/13452178494/job/37588450279
Not sure it's working correctly.
When I try `devenv version` from the host project I get `1.3.0`
And when inside IHP I got `1.4.0`
> Upgrade devenv  to 1.4.1

- CONTRIBUTING.md
@mpscholten I want to debug what's the value set on [mainInProjectDirectory](https://github.com/digitallyinduced/ihp/blob/012c7a3c03437109426c64b7c98189b6d639ca44/ihp-ide/exe/IHP/IDE/DevServer.hs#L49-L51)
```diff
mainInProjectDirectory :: FilePath -> IO ()
mainInProjectDirectory projectDir = do
cwd <- Directory.getCurrentDirectory
+    liftIO $ putStrLn $ "mainInProjectDirectory: " <> cwd
+    liftIO $ putStrLn $ "projectDir: " <> projectDir
```
So I figured I need to run the DevServer via ghci. PR tries to fix the docs about it, but I get this error.
I tried to `nix flake lock --update-input ihp` from the host project, but it doesn't help
> Updater docs on developing the DevServer

- ihp-hsx/Test/IHP/HSX/QQSpec.hs
- ihp-hsx/blaze/IHP/HSX/ToHtml.hs
- ihp-hsx/ihp-hsx.cabal
- ihp-hsx/parser/IHP/HSX/HsExpToTH.hs
- ihp-hsx/parser/IHP/HSX/Parser.hs
Fix the version dependent bits of HsExpToTH to support 9.10.x and 9.12.x.
Bump the version bounds in ihp-hsx.cabal.
Use explicit imports for Data.Text, as it now exports a `show` that conflicts with the `show` in Prelude.
> ihp-hsx: Add support for GHC 9.10.x and 9.12.x

- IHP/FileStorage/Preprocessor/ImageMagick.hs
This PR fixes issue #2071 by replacing the deprecated convert command with the recommended magick command in the file ihp/IHP/FileStorage/Preprocessor/ImageMagick.hs. This change ensures compatibility with ImageMagick version 7 and above.
> Fix deprecated 'convert' command to 'magick' in ImageMagick.hs

- IHP/Controller/Redirect.hs
- IHP/Server.hs
Makes redirects more flexible when an IHP app is running on multiple domains
> Use Approot middleware for redirects

- ihp-hsx/changelog.md
- ihp-hsx/ihp-hsx.cabal
@iteratee I'll push the lucid2 changes to hackage via version 1.5.0 in a few minutes.
Maybe we should refactor the package structure such that we have two hackage packages. Otherwise all users of ihp-hsx will always depend on lucid2 (e.g. splitting into ihp-hsx-parser, ihp-hsx-blaze and ihp-hsx-lucid2)
> ihp-hsx: version 1.5.0

- Guide/package-management.markdown
very minor documentation fix to avoid possible confusion (though could be useful on its own as an example of how to set to local ihp checkout?)
> Doc: Change ihp.url back to default in postgres example

- Guide/package-management.markdown
- UPGRADE.md
It seems like if you just do `nix flake metadata nixpkgs` it takes your global default nixpkgs or something, not the one from the local flake.nix. 
(My previous attempt seems like it gave the wrong hash, I didn't notice at first since it was cached I guess.)
> Doc: `nix flake metadata` needs `inputs-from .`
